// scenes/level3.js — 二十以内 (Up to 20). Teaches the
// "split the 2-digit into 10 + ones, add the ones to b, then add 10
// to the sum" strategy in 3 explicit steps. No ten-frame, no cells —
// per the user ("不需要格子"), just equations on screen.
//
// Round data shape: { a, b, answer } where a is a 2-digit number
// with tens digit = 1 (i.e. a ∈ [11, 19]) and b is a 1-digit number.
// Invariant: ones(a) + b ≤ 10 so the third step's add doesn't carry.
// Derived per round: ones = a % 10, sum = ones + b, answer = a + b.
//
// The persistent anchor ("a + b = ?") sits at the TOP of the screen
// in the largest font — it's the goal the child is working toward
// and never disappears between teaching beats. Each step shows
// smaller sub-equations below it:
//
//   Step 1 — Split:   sub "a = 10 + ?" → child picks ones.
//                     Audio: "11+8等于几，我们先把 11 进行拆分，
//                            拆成十加几"
//                     Deferred equation: the sub-question renders
//                     AFTER the audio finishes, so the kid hears
//                     the strategy before seeing the question.
//   Step 2 — Add:     visual aid on top "(10 + ones) + b = ?"
//                     sub on the bottom "ones + b = ?" → child picks sum.
//                     Audio: "个位相加 [ones] 加 [b] 等于几"
//   Step 3 — Total:   sub "10 + sum = ?" → child picks answer.
//                     Audio: "十 加 [sum] 等于几"
//                     After step 3 correct, the anchor reveals too
//                     and a reward audio reads "a+b=answer" (the
//                     full equation as a celebration sentence).

import createRoundScene, { LAYOUT, options } from "./roundScene.js";
import expression from "../components/expression.js";
import {
  INK, FONT, YELLOW, BLUE, PINK, ORANGE,
} from "../components/theme.js";

const TEN = 10;
const COL_BIG   = BLUE;    // the 2-digit addend (a)
const COL_SMALL = PINK;    // the 1-digit addend (b)
const COL_TEN   = YELLOW;  // the literal "10" in sub-questions
const COL_NEED  = ORANGE;  // the unknown / just-computed slot

// Persistent anchor ("a + b = ?") rendered at the top, large.
function anchorSlots(round, sumSlot) {
  return {
    slots: [round.a, "+", round.b, "=", sumSlot],
    colors: [COL_BIG, undefined, COL_SMALL, undefined, undefined],
  };
}

// Step 2 visual aid: parenthesized full equation "(10 + ones) + b = ?".
// Lives on ctx.parensForm so the roundScene's `setEquation` (the "active
// sub-question") doesn't overwrite it. Mirrors L1's parenthesizedForm
// pattern — the equation that ties the split back to the original
// problem sits above the simplified sub-question that the child picks.
//
// Colors stay consistent with step 1's reveal: 10 = YELLOW, ones = ORANGE
// (just computed in step 1), b = PINK (the small addend). The "?" is a
// muted/ink slot — it's the full answer, still unknown.
function l3Step2ParensForm(ctx, ones, b, answer = null) {
  if (ctx.parensForm) ctx.parensForm.destroy();
  const lastSlot = answer != null ? String(answer) : "?";
  const slots = ["(", TEN, "+", ones, ")", "+", b, "=", lastSlot];
  const colors = [
    undefined,            // "("
    COL_TEN,              // "10"
    undefined,            // "+"
    COL_NEED,             // ones (just computed)
    undefined,            // ")"
    undefined,            // "+"
    COL_SMALL,            // b
    undefined,            // "="
    answer != null ? INK : undefined, // "?" (muted) or revealed
  ];
  ctx.parensForm = expression(ctx.k, {
    slots,
    colors,
    x: LAYOUT.barX,
    y: 340,
    size: 76,
  });
}

// Per-step L3 audio. Each step is one pre-baked composite mp3
// generated by tools/build-composite-audio.mjs — one mp3 per
// (a, b) / (ones, b) / (sum) combination from data/levels.json.
// Returns a single-element array so the existing playSequence /
// playAfter / onComplete machinery still works (one cue = same
// event-driven chain).
//
// Step 1 — Split: "11+8等于几，我们先把 11 进行拆分，拆成十加几"
function buildL3Step1Ids(a, b) {
  return [`l3-s1-${a}-${b}`];
}

// Step 2 — Add the two ones: "个位相加 [ones] 加 [b] 等于几"
function buildL3Step2Ids(ones, b) {
  return [`l3-s2-${ones}-${b}`];
}

// Step 3 — Add 10 and the sum: "十 加 [sum] 等于几"
function buildL3Step3Ids(sum) {
  return [`l3-s3-${sum}`];
}

// After step 3 correct, read the full equation as a reward:
// "11+8=19". One composite mp3 per (a, b, answer).
function buildL3RewardIds(a, b, answer) {
  return [`l3-rwd-${a}-${b}-${answer}`];
}

// Fires a per-step L3 audio chain. Three cases (same pattern as L2 —
// see scenes/level2.js for the full rationale):
//
//   1. Step 1 on round 0: chain off the one-time entry greeting
//      (lvl-3-intro). The greeting plays on scene start, this step
//      waits for its `ended` event + 800ms so the greeting lands
//      first.
//
//   2. Any step after a correct pick (round 0 step 2/3, round 1+ all
//      steps): chain off panda-celebrate — the last cue of the cheer
//      chain ("好棒"). The new prompt starts AFTER the cheer lands,
//      with 400ms breath between. Without this, the cheer and the
//      new prompt overlap and feel crammed together.
//
//   3. Fallback (no prior audio to chain off): play immediately with
//      a small render-settle delay.
function fireL3StepAudio(ctx, ids, stepNumber, onComplete) {
  if (ctx.ri === 0 && stepNumber === 1) {
    window.PandaAudio.playAfter("lvl-3-intro", ids, {
      gapMs: 800,
      seqGapMs: 40,
    }, onComplete);
    return;
  }
  // After a correct pick, the celebration chain ends with
  // "panda-celebrate" — chain the step audio off its `ended` event
  // so the next step starts immediately when the cheer finishes,
  // with no setTimeout and no overlap with the cheer tail.
  if (ctx.lastEncourageId) {
    window.PandaAudio.playAfter("panda-celebrate", ids, {
      gapMs: 400,
      seqGapMs: 40,
    }, onComplete);
    return;
  }
  window.PandaAudio.playSequence(ids, 40, 100, onComplete);
}

export default createRoundScene({
  levelId: 3,
  sceneName: "level3",
  introCue: "lvl-3-intro",
  // Three teaching beats. Labels are the visible step-bar text — short,
  // verb-shaped Chinese that names the strategy of each beat.
  stepLabels: ["拆十位", "加个位", "加起来"],

  steps: [
    // Step 1 — Split: a = 10 + ones.
    (ctx, round) => {
      const ones = round.a % TEN;
      // Persistent anchor at top, big.
      ctx.setAnchorEquation(anchorSlots(round, "?"), { y: 220 });
      // Sub-question: a = 10 + ? (the "?" slot in ORANGE for the unknown).
      // Deferred until the Step 1 audio has actually finished — mirroring
      // the L1 step 1 pattern. The kid hears the question first, then
      // sees what they're being asked.
      const subQuestion = {
        slots: [round.a, "=", "10", "+", "?"],
        colors: [COL_BIG, undefined, COL_TEN, undefined, COL_NEED],
      };
      const subQuestionOpts = { y: 440, size: 82 };
      // Per-step audio: "11+8等于几，我们先把 11 进行拆分，拆成十加几".
      // Reveal the sub-question from its `ended` event (PandaAudio
      // forwards onComplete to fire after the LAST cue's `ended` event).
      fireL3StepAudio(
        ctx, buildL3Step1Ids(round.a, round.b), 1,
        () => ctx.setEquation(subQuestion, subQuestionOpts),
      );
      return {
        deferEquation: true,
        equation: subQuestion,
        equationOpts: subQuestionOpts,
        question: {
          correct: ones,
          values: options(ones, { min: 0, max: 9 }),
        },
        onAdvance: () => {
          // Reveal the ones digit in place; keep ORANGE so it reads as
          // the slot the child just filled (consistent with L2's
          // COL_NEED for just-computed values).
          ctx.setEquation({
            slots: [round.a, "=", "10", "+", ones],
            colors: [COL_BIG, undefined, COL_TEN, undefined, COL_NEED],
          }, { y: 440, size: 82 });
        },
      };
    },
    // Step 2 — Add the ones to b: ones + b = sum.
    // Visual aid on top shows the parenthesized full equation
    // "(10 + ones) + b = ?" so the eye links the split (10 + ones) back
    // to the original a + b. The simplified sub-question "ones + b = ?"
    // sits below — that's what the child actually picks. Mirrors L1's
    // parenthesizedForm + sub-question layout.
    (ctx, round) => {
      const ones = round.a % TEN;
      const sum = ones + round.b;
      // Persistent anchor still "?" (waiting for the final reveal).
      ctx.setAnchorEquation(anchorSlots(round, "?"), { y: 220 });
      // Parenthesized full equation as a visual aid (mirrors L1 step 2).
      l3Step2ParensForm(ctx, ones, round.b);
      // Sub-question: ones + b = ? — ones stays ORANGE so it visually
      // connects to the value just filled in step 1.
      ctx.setEquation({
        slots: [ones, "+", round.b, "=", "?"],
        colors: [COL_NEED, undefined, COL_SMALL, undefined, COL_NEED],
      }, { y: 440, size: 82 });
      // Per-step audio: "个位相加 [ones] 加 [b] 等于几".
      fireL3StepAudio(ctx, buildL3Step2Ids(ones, round.b), 2);
      return {
        question: {
          correct: sum,
          values: options(sum, { min: 1, max: 10 }),
        },
        onAdvance: () => {
          // Reveal the sub-question's "?" with sum — the kid just
          // filled in this slot. The parenthesized form on top stays
          // as "(10 + ones) + b = ?" — its "?" is the full answer,
          // which is still unknown until step 3.
          ctx.setEquation({
            slots: [ones, "+", round.b, "=", sum],
            colors: [COL_NEED, undefined, COL_SMALL, undefined, COL_NEED],
          }, { y: 440, size: 82 });
        },
      };
    },
    // Step 3 — Total: 10 + sum = answer.
    (ctx, round) => {
      const ones = round.a % TEN;
      const sum = ones + round.b;
      // Persistent anchor still "?" — only revealed at the very end.
      ctx.setAnchorEquation(anchorSlots(round, "?"), { y: 220 });
      // Parenthesized form stays as a visual aid (no change from step 2).
      l3Step2ParensForm(ctx, ones, round.b);
      // Sub-question: 10 + sum = ? — sum carries the ORANGE color so
      // the child can see it's the result of step 2.
      ctx.setEquation({
        slots: [TEN, "+", sum, "=", "?"],
        colors: [COL_TEN, undefined, COL_NEED, undefined, COL_NEED],
      }, { y: 440, size: 82 });
      // Per-step audio: "十 加 [sum] 等于几".
      fireL3StepAudio(ctx, buildL3Step3Ids(sum), 3);
      return {
        question: {
          correct: round.answer,
          // Answer range: a (11-19) + b (1-9), with ones+b ≤ 10, so
          // answer is in [12, 20]. Show options in [11, 20] for
          // breathing room either side.
          values: options(round.answer, { min: 11, max: 20 }),
        },
        onAdvance: () => {
          // Reveal the persistent anchor with the final answer.
          ctx.setAnchorEquation(anchorSlots(round, round.answer), { y: 220 });
          // Reveal the sub-question — sum in ORANGE, answer in INK
          // (the final settled answer; orange has done its job).
          ctx.setEquation({
            slots: [TEN, "+", sum, "=", round.answer],
            colors: [COL_TEN, undefined, COL_NEED, undefined, INK],
          }, { y: 440, size: 82 });
          // Reveal the parenthesized form's "?" with the full answer
          // — every "?" on screen now has a number, and the kid sees
          // the strategy land: 11 = 10 + 1, 1 + 8 = 9, 10 + 9 = 19.
          l3Step2ParensForm(ctx, ones, round.b, round.answer);
          // Reward audio: "11+8=19" — the full equation as a
          // celebration sentence. Chained off panda-celebrate (the
          // cheer chain's last cue) so it doesn't overlap with the
          // celebration. roundScene awaits the returned Promise so
          // the kid hears "11+8=19" before the next round's
          // greeting fires.
          return new Promise((resolve) => {
            window.PandaAudio.playAfter(
              "panda-celebrate",
              buildL3RewardIds(round.a, round.b, round.answer),
              { gapMs: 200, seqGapMs: 40 },
              resolve,
            );
          });
        },
      };
    },
  ],
});