// scenes/subtractionLevels.js — L6/L7/L8 single-file level module.
//
// v2 redesign (2026-08-16, per user feedback):
//   L6 — drop the duplicate sub-equation ("a - b = ?") that mirrored the
//        anchor. Add per-round step-1 audio ("a 减 b 等于几") and the
//        answer read-back ("a 减 b 等于 answer"). Filter a === b from
//        the pool (see data/pools.js generateL6Pool).
//   L7 — replace the one-shot "render the split, render the sub,
//        render the result" pattern with an L5-style persistent
//        teaching diagram: anchor on top, split (a = 10 + □) below it,
//        sub (□ - b = □) below that, result (10 + □ = ?) on the bottom,
//        with decomposition lines drawn from anchor.a → split, and from
//        each row's "just-solved" slot to the next row's matching slot.
//        The lines stay visible across the whole round so the kid
//        always sees "this comes from that" — the visual frame of the
//        strategy. Per user feedback 2026-08-16: "level7:没有参考
//        level5，有分解的线条表示。有线条小孩好理解些".
//   L8 — kept on the simpler "render-this-step-only" pattern from v1.
//        The borrow path is structurally identical to L7 minus the
//        first half of the strategy, so future work could collapse the
//        two into one shared scaffold; out of scope for this pass.
//
// Audio cues (composite, generated by tools/build-audio-tencent.mjs):
//   l6-s1-{a}-{b}                  "{a}减{b}等于几"
//   l6-rwd-{a}-{b}-{answer}        "{a}减{b}等于{answer}"
//   l7-s1-{a}-{b}                  "{a}减{b}等于几，我们先把{a}拆成十加几"
//   l7-s2-{ones}-{b}               "个位相减{ones}减{b}等于几"
//   l7-s3-{diff}                   "十加{diff}等于几"
//   l7-rwd-{a}-{b}-{answer}        "{a}减{b}等于{answer}"

import createRoundScene, { LAYOUT, options } from "./roundScene.js?v=20260816";
import { poolGens } from "../data/pools.js?v=20260816";
import expression from "../components/expression.js?v=20260816";
import drawLink from "../components/drawLink.js?v=20260816";
import {
  BLUE, PINK, YELLOW, ORANGE, INK,
} from "../components/theme.js?v=20260816";

const COL_BIG   = BLUE;    // the 2-digit minuend (a)
const COL_SMALL = PINK;    // the 1-digit subtrahend (b)
const COL_TEN   = YELLOW;  // the literal "10"
const COL_NEED  = ORANGE;  // unknown / just-computed slot

// ---------- shared slot helpers ----------------------------------------

function subtractionSlots(round, answer = "?") {
  return {
    slots: [round.a, "-", round.b, "=", answer],
    colors: [COL_BIG, undefined, COL_SMALL, undefined, answer === "?" ? COL_NEED : undefined],
    reserve: [round.a, "-", round.b, "=", round.answer],
  };
}

// L7 anchor (a - b = ?) — top of the persistent diagram. Same shape as
// the L5 anchor (a + b = ?) but with "-" instead of "+", and the minuend
// colored BLUE per L6.
function l7AnchorSlots(round, sumSlot) {
  return {
    slots: [round.a, "-", round.b, "=", sumSlot],
    colors: [COL_BIG, undefined, COL_SMALL, undefined, sumSlot === "?" ? COL_NEED : undefined],
    reserve: [round.a, "-", round.b, "=", round.answer],
  };
}

// L7 split row: "a = 10 + □" — the kid picks the ones digit. Reserve
// pins the "□" to its widest lifetime content so the row stays the same
// width across the step-1 reveal.
function l7SplitSlots(round, onesSlot = "□") {
  return {
    slots: [round.a, "=", 10, "+", onesSlot],
    colors: [COL_BIG, undefined, COL_TEN, undefined, COL_NEED],
    reserve: [round.a, "=", 10, "+", "□"],
  };
}

// L7 sub row: "ones - b = □" — the kid picks the ones-difference. Slot
// 0 (ones) stays COL_NEED even after reveal so the visual line from
// split → sub carries the same color all the way (per L5's split1Row
// convention).
function l7SubSlots(round, diffSlot = "□") {
  return {
    slots: [round.ones, "-", round.b, "=", diffSlot],
    colors: [COL_NEED, undefined, COL_SMALL, undefined, COL_NEED],
    reserve: [round.ones, "-", round.b, "=", "□"],
  };
}

// L7 result row: "10 + diff = ?" — same shape as L4's bottom row. Slot
// 2 (diff) stays COL_NEED after reveal (line source for L3).
function l7ResultSlots(round, diff, answerSlot = "?") {
  return {
    slots: [10, "+", diff, "=", answerSlot],
    colors: [COL_TEN, undefined, COL_NEED, undefined, answerSlot === "?" ? COL_NEED : INK],
    reserve: [10, "+", "□", "=", round.answer],
  };
}

// ---------- L7 layout ---------------------------------------------------

// 4 stacked rows — anchor (top) → split → sub → result (bottom). Each
// row is 80px below the previous so the decomposition lines have enough
// vertical runway without crowding the digits (size 60-80 boxes are
// ~60-80px tall; 80-90px gaps read as a comfortable stride).
const Y_ANCHOR = 240;
const Y_SPLIT  = 380;
const Y_SUB    = 540;
const Y_RESULT = 700;

const ANCHOR_SIZE = 80;
const ROW_SIZE    = 60;

// L7 anchor + split + sub + result are persistent across the whole
// round (same pattern as L4/L5). The rendering of each row is a fresh
// expression() call so a slot reveal (step 1 → step 2) recreates the
// row with the new content; the reserve pattern keeps the slot
// centers pinned so the lines drawn against them don't drift.
function renderL7Row(ctx, key, slots, opts) {
  if (ctx[key]) ctx[key].destroy();
  ctx[key] = expression(ctx.k, {
    ...slots,
    // Centered on the step bar's x. ctx.arrowsRoot is positioned at
    // (0, 0) for the drawLink parent — using its pos.x would shove the
    // row off to the left edge (regression seen 2026-08-16 in the
    // L7 step-2 screenshot where the split row clipped at x≈0).
    x: LAYOUT.barX,
    y: opts.y,
    size: opts.size,
  });
  return ctx[key];
}

function redrawL7Links(ctx) {
  ctx.arrowNodes?.forEach((n) => n.destroy());
  ctx.arrowNodes = [];
  const anchor = ctx.l7AnchorNode;
  const split  = ctx.l7SplitNode;
  const sub    = ctx.l7SubNode;
  const result = ctx.l7ResultNode;
  if (!anchor?.slotCenters) return;
  const pts = [];

  // L1: anchor.a → split[2] ("10"). Ten-half of the decomposition,
  // color matches COL_TEN so the line visually pairs with the slot.
  if (split?.slotCenters?.[2] != null && anchor.slotCenters[0] != null) {
    pts.push({
      from: { x: anchor.slotCenters[0], y: anchor.slotY + anchor.slotSizes[0] / 2 },
      to:   { x: split.slotCenters[2], y: split.slotY - split.slotSizes[2] / 2 },
      color: COL_TEN,
    });
  }
  // L1a: anchor.a → split[4] ("□"). Ones-half of the decomposition,
  // color COL_NEED so the box on the receiving end matches.
  if (split?.slotCenters?.[4] != null && anchor.slotCenters[0] != null) {
    pts.push({
      from: { x: anchor.slotCenters[0], y: anchor.slotY + anchor.slotSizes[0] / 2 },
      to:   { x: split.slotCenters[4], y: split.slotY - split.slotSizes[4] / 2 },
      color: COL_NEED,
    });
  }
  // L2: split[4] (the just-revealed ones box) → sub[0] (ones digit in
  // "ones - b = ?"). Both are COL_NEED so the line carries the color
  // through. Renders once sub is introduced (step 2).
  if (split?.slotCenters?.[4] != null && sub?.slotCenters?.[0] != null) {
    pts.push({
      from: { x: split.slotCenters[4], y: split.slotY + split.slotSizes[4] / 2 },
      to:   { x: sub.slotCenters[0], y: sub.slotY - sub.slotSizes[0] / 2 },
      color: COL_NEED,
    });
  }
  // L3: sub[4] (just-revealed diff box) → result[2] (diff digit in
  // "10 + diff = ?"). Renders once result is introduced (step 3).
  if (sub?.slotCenters?.[4] != null && result?.slotCenters?.[2] != null) {
    pts.push({
      from: { x: sub.slotCenters[4], y: sub.slotY + sub.slotSizes[4] / 2 },
      to:   { x: result.slotCenters[2], y: result.slotY - result.slotSizes[2] / 2 },
      color: COL_NEED,
    });
  }

  for (const p of pts) {
    ctx.arrowNodes.push(drawLink(ctx.k, ctx.arrowsRoot, p.from, p.to, p.color, 7, 0.4));
  }
}

// ---------- shared audio chain helpers ---------------------------------

// Fires a per-step audio cue chain. Same pattern as L4/L5 (see
// scenes/level5.js::fireL5StepAudio): chain off the cheer chain's last
// cue when there's one (gap 400ms breath), otherwise play immediately
// with a small render-settle delay.
function fireSubtractionStepAudio(ctx, ids, _stepNumber, onComplete) {
  if (ctx.lastEncourageId) {
    window.PandaAudio.playAfter(ctx.lastEncourageId, ids, {
      gapMs: 400, seqGapMs: 40,
    }, onComplete);
    return;
  }
  window.PandaAudio.playSequence(ids, 40, 100, onComplete);
}

// ---------- L6 audio cue builders --------------------------------------

function buildL6Step1Ids(a, b) { return [`l6-s1-${a}-${b}`]; }
function buildL6RewardIds(a, b, answer) { return [`l6-rwd-${a}-${b}-${answer}`]; }

// ---------- L7 audio cue builders --------------------------------------

function buildL7Step1Ids(a, b) { return [`l7-s1-${a}-${b}`]; }
function buildL7Step2Ids(ones, b) { return [`l7-s2-${ones}-${b}`]; }
function buildL7Step3Ids(diff) { return [`l7-s3-${diff}`]; }
function buildL7RewardIds(a, b, answer) { return [`l7-rwd-${a}-${b}-${answer}`]; }

// ---------- L6 ----------------------------------------------------------

// L6 is a single-step level — the kid reads the equation and picks the
// answer. Per user feedback 2026-08-16 ("没有介绍的声音，用腾讯生成"),
// the per-round step-1 audio IS the entry prompt. After correct pick the
// reward audio reads the full equation as a celebration sentence; the
// advance is gated on that audio finishing (same Promise pattern as L5
// step 5).
export const level6 = createRoundScene({
  levelId: 6,
  sceneName: "level6",
  poolGen: () => poolGens[6](),
  sampleSize: 10,
  stepLabels: ["算一算"],
  steps: [
    (ctx, round) => {
      // Anchor at the top — the SAME shape as L4's anchor, sized
      // smaller (96 vs L4's 100) since there's no second row below it
      // competing for vertical space.
      ctx.setAnchorEquation(subtractionSlots(round), { y: 280, size: 96 });
      fireSubtractionStepAudio(ctx, buildL6Step1Ids(round.a, round.b), 1);
      return {
        // NO equation — the anchor IS the equation. The previous version
        // rendered the same "a - b = ?" row again at y=460, which made
        // the screen read as "the same equation twice". Per user feedback
        // 2026-08-16: "表达式重复了两次，没必要".
        question: {
          correct: round.answer,
          values: options(round.answer, { min: 0, max: 10 }),
        },
        onAdvance: () => {
          ctx.setAnchorEquation(subtractionSlots(round, round.answer), { y: 280, size: 96 });
          return new Promise((resolve) => {
            window.PandaAudio.playAfter(
              ctx.lastEncourageId,
              buildL6RewardIds(round.a, round.b, round.answer),
              { gapMs: 200, seqGapMs: 40 },
              resolve,
            );
          });
        },
      };
    },
  ],
});

// ---------- L7 ----------------------------------------------------------

// 3 teaching beats mirroring L5 minus the b decomposition (L7's b fits
// inside ones, no need to split it). Diagram layout per "有分解的线条表示":
//   anchor   "a - b = ?"           y=240   (top, large, persistent)
//   split    "a = 10 + □"          y=380   (introduced step 1)
//   sub      "□ - b = □"           y=540   (introduced step 2)
//   result   "10 + □ = ?"          y=700   (introduced step 3)
// Each row is rebuilt fresh on slot reveal; reserve pins keep the slot
// centers stable across reveals so the lines drawn against them don't
// drift (same pattern as L4/L5).
const l7Steps = [
  // Step 1 — 拆 a. Introduce the split row. Audio: "a 减 b 等于几，
  // 我们先把 a 拆成十加几". Kid picks the ones digit.
  (ctx, round) => {
    ctx.setAnchorEquation(l7AnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    fireSubtractionStepAudio(ctx, buildL7Step1Ids(round.a, round.b), 1, () => {
      renderL7Row(ctx, "l7SplitNode", l7SplitSlots(round), { y: Y_SPLIT, size: ROW_SIZE });
      redrawL7Links(ctx);
    });
    return {
      question: {
        correct: round.ones,
        // Step 1 options: ones digit, [1, 9]. The reserve covers [0,
        // 9] but ones ≥ 1 by pool rule so the kid never sees "0".
        values: options(round.ones, { min: 1, max: 9 }),
      },
      onAdvance: () => {
        renderL7Row(ctx, "l7SplitNode", l7SplitSlots(round, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
        redrawL7Links(ctx);
      },
    };
  },

  // Step 2 — 减个位. Anchor + split stay. Introduce the sub row
  // "ones - b = ?". Audio: "个位相减 ones 减 b 等于几". Kid picks diff.
  (ctx, round) => {
    const diff = round.ones - round.b;
    ctx.setAnchorEquation(l7AnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderL7Row(ctx, "l7SplitNode", l7SplitSlots(round, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
    fireSubtractionStepAudio(ctx, buildL7Step2Ids(round.ones, round.b), 2, () => {
      renderL7Row(ctx, "l7SubNode", l7SubSlots(round), { y: Y_SUB, size: ROW_SIZE });
      redrawL7Links(ctx);
    });
    return {
      question: {
        correct: diff,
        // Sub row answer range: [0, ones-1]. diff can be 0 (e.g. 11-1
        // → ones=1, b=1, diff=0) so options span [0, max(0, ones-1)].
        values: options(diff, { min: 0, max: Math.max(0, round.ones - 1) }),
      },
      onAdvance: () => {
        renderL7Row(ctx, "l7SubNode", l7SubSlots(round, diff), { y: Y_SUB, size: ROW_SIZE });
        redrawL7Links(ctx);
      },
    };
  },

  // Step 3 — 合起来. Anchor + split + sub stay. Introduce the result
  // row "10 + diff = ?". Audio: "十加 diff 等于几". Kid picks answer.
  (ctx, round) => {
    const diff = round.ones - round.b;
    ctx.setAnchorEquation(l7AnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderL7Row(ctx, "l7SplitNode", l7SplitSlots(round, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
    renderL7Row(ctx, "l7SubNode", l7SubSlots(round, diff), { y: Y_SUB, size: ROW_SIZE });
    fireSubtractionStepAudio(ctx, buildL7Step3Ids(diff), 3, () => {
      renderL7Row(ctx, "l7ResultNode", l7ResultSlots(round, diff), { y: Y_RESULT, size: ROW_SIZE });
      redrawL7Links(ctx);
    });
    return {
      question: {
        correct: round.answer,
        // Answer range: [10, 18] (a in [11,19], b in [1, ones] → answer
        // ∈ [a - ones, a - 1] ⊆ [10, 18]).
        values: options(round.answer, { min: 10, max: 18 }),
      },
      onAdvance: () => {
        // Reveal the answer in the anchor (slot 4) and the result
        // row's slot 4, just like L5 step 5. The persistent diagram
        // stays — no row is torn down; only the answer slots are
        // rewritten. Per user feedback 2026-08-12 (L4 step 3): "选中
        // 正确答案之后，你把所有都清了，更不对了" — same lesson
        // applies here, so we keep all four rows and just fill in the
        // two answer slots.
        ctx.setAnchorEquation(l7AnchorSlots(round, round.answer), { y: Y_ANCHOR, size: ANCHOR_SIZE });
        renderL7Row(ctx, "l7ResultNode", l7ResultSlots(round, diff, round.answer), { y: Y_RESULT, size: ROW_SIZE });
        redrawL7Links(ctx);
        return new Promise((resolve) => {
          window.PandaAudio.playAfter(
            ctx.lastEncourageId,
            buildL7RewardIds(round.a, round.b, round.answer),
            { gapMs: 200, seqGapMs: 40 },
            resolve,
          );
        });
      },
    };
  },
];

export const level7 = createRoundScene({
  levelId: 7,
  sceneName: "level7",
  poolGen: () => poolGens[7](),
  sampleSize: 10,
  stepLabels: ["拆一拆", "减个位", "合起来"],
  steps: l7Steps,
});

// ---------- L8 (unchanged from v1) --------------------------------------

// 十几减几（退位） — 3 steps: borrow a ten, find the rest, subtract the
// rest from ten. Kept on the simpler "render this step's equation only"
// pattern from v1; future work could collapse into the L7 diagram if
// the user wants L8 to mirror L7's line-driven teaching.
//
// Strategy (each round precomputes `rest = b - ones` in the pool):
//   step 1 — a - □ = 10        kid picks ones (the part to borrow)
//   step 2 — b = ones + □      kid picks rest (the leftover)
//   step 3 — 10 - rest = ?     kid picks answer
function borrowSteps() {
  return [
    // Step 1 — "borrow": take the a's ones digit off so we land on 10.
    // Kid picks ones (the part being subtracted from a).
    (ctx, round) => {
      ctx.setAnchorEquation(subtractionSlots(round), { y: 220 });
      return {
        equation: {
          slots: [round.a, "-", "□", "=", 10],
          colors: [COL_BIG, undefined, COL_NEED, undefined, COL_TEN],
          reserve: [round.a, "-", "□", "=", 10],
        },
        equationOpts: { y: 460, size: 88 },
        question: { correct: round.ones, values: options(round.ones, { min: 1, max: 8 }) },
        onAdvance: () => ctx.setEquation({
          slots: [round.a, "-", round.ones, "=", 10],
          colors: [COL_BIG, undefined, COL_NEED, undefined, COL_TEN],
          reserve: [round.a, "-", "□", "=", 10],
        }, { y: 460, size: 88 }),
      };
    },
    // Step 2 — "find rest": b = ones + rest. The kid just picked ones
    // (the part borrowed from a); the rest is what's left of b after
    // that. Kid picks rest.
    (ctx, round) => {
      ctx.setAnchorEquation(subtractionSlots(round), { y: 220 });
      return {
        equation: {
          slots: [round.b, "=", round.ones, "+", "□"],
          colors: [COL_SMALL, undefined, COL_NEED, undefined, COL_NEED],
          reserve: [round.b, "=", round.ones, "+", "□"],
        },
        equationOpts: { y: 460, size: 88 },
        question: { correct: round.rest, values: options(round.rest, { min: 1, max: 8 }) },
        onAdvance: () => ctx.setEquation({
          slots: [round.b, "=", round.ones, "+", round.rest],
          colors: [COL_SMALL, undefined, COL_NEED, undefined, COL_NEED],
          reserve: [round.b, "=", round.ones, "+", "□"],
        }, { y: 460, size: 88 }),
      };
    },
    // Step 3 — "subtract": 10 - rest = ?. Kid picks the answer.
    (ctx, round) => {
      ctx.setAnchorEquation(subtractionSlots(round), { y: 220 });
      return {
        equation: {
          slots: [10, "-", round.rest, "=", "□"],
          colors: [COL_TEN, undefined, COL_NEED, undefined, COL_NEED],
          reserve: [10, "-", round.rest, "=", round.answer],
        },
        equationOpts: { y: 460, size: 88 },
        question: { correct: round.answer, values: options(round.answer, { min: 2, max: 10 }) },
        onAdvance: () => {
          ctx.setAnchorEquation(subtractionSlots(round, round.answer), { y: 220 });
          ctx.setEquation({
            slots: [10, "-", round.rest, "=", round.answer],
            colors: [COL_TEN, undefined, COL_NEED, undefined, undefined],
            reserve: [10, "-", round.rest, "=", round.answer],
          }, { y: 460, size: 88 });
        },
      };
    },
  ];
}

export const level8 = createRoundScene({
  levelId: 8,
  sceneName: "level8",
  poolGen: () => poolGens[8](),
  sampleSize: 10,
  stepLabels: ["减到十", "找剩余", "再减"],
  steps: borrowSteps(),
});