import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
const URL = "http://localhost:8126/";
const OUT = "tmp-screens";
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH });
const ctx = await browser.newContext({ viewport: { width: 1366, height: 1024 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.on("pageerror", (e) => console.error("[pageerror]", e.message));
await page.goto(URL, { waitUntil: "networkidle" });
await page.waitForTimeout(500);
await page.mouse.click(683, 512);
await page.waitForTimeout(400);
const canvas = await page.$("canvas");
const box = await canvas.boundingBox();
await page.mouse.click(box.x + 1166, box.y + 200);
await page.waitForTimeout(900);
// Cloud card is at i=2, x=683
await page.mouse.click(box.x + 683, box.y + 600);
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/cloud-after-small.png` });
console.log("[screenshot] captured gameCloud");
await browser.close();
