// main.js — Panda H5 (Kaplay) boot + audio pool + iPad viewport plumbing.
// No build step. Loads scenes and components from ./scenes and ./components.
//
// levels data is inlined as a JS const (not fetched, not JSON-imported) so
// the game boots under the file:// protocol on iPad Safari, where fetch()
// is blocked and JSON module imports require the assert { type: "json" }
// attribute that older WebKit builds do not honor. data/levels.json stays
// in the repo as a single source of truth for offline editing.

import kaplay from "./assets/vendor/kaplay.mjs";
import "./save.js?v=20260812";
import { poolGens } from "./data/pools.js?v=20260812";
import { ALL_SPRITE_NAMES } from "./data/whackPack.js?v=20260815";

// Per-level round data is now generated on the fly by data/pools.js —
// each level scene passes a `poolGen` to createRoundScene which samples
// 10 rounds per session from the full enumeration. This inline levelsData
// only carries metadata (title, intro) for the menu UI.
//
// Five math levels (added 2026-08-15 when L5「十几加十几」was added):
//   L1 三数相加<10  sum of three 1-digit addends ≤ 10
//   L2 两个数凑十   three addends where two sum to 10
//   L3 凑十法       single-digit pair whose sum > 10, teach the
//                   make-a-ten decomposition
//   L4 二十以内     teen + digit, no-carry, use 10+ones strategy
//   L5 十几加十几   two teens + two teens, no carry, 5-step decomposition
const levelsData = {
  "levels": [
    { "id": 1, "title": "三数相加" },
    { "id": 2, "title": "两数凑十" },
    { "id": 3, "title": "凑十法" },
    { "id": 4, "title": "二十以内" },
    { "id": 5, "title": "十几加十几" },
  ],
};

const CUE_IDS = [
// Generated by tools/emit-cue-ids.mjs from assets/audio/*.mp3. Re-run
// that script after `npm run audio:build` to pick up newly synthesized
// cues. Previously hand-curated; this regeneration fixes the L2 / L3
// silent-bug (CUE_IDS was missing every `l1-intro-mt-*`, every
// `l2-s1-` / `l2-s2-` / `l2-s3-` / `l2-s4-` / `l2-cmp-` / `l2-s4s-`
// cue, and every `l3-s4-` / `l3-cmp-` / `l3-s4s-` cue reachable from
// the live pool — see commit log for the diagnosis).
  "boat-done", "boat-intro", "boat-pair", "bounce-done", "bounce-intro", "bounce-pop",
  "cloud-done", "cloud-intro", "cloud-pair", "daily-done", "enc-first-1", "enc-first-2",
  "enc-first-3", "enc-first-4", "enc-level-1", "enc-level-2", "enc-level-3", "enc-level-4",
  "enc-near-1", "enc-near-2", "enc-near-3", "enc-specific-decomp", "enc-specific-double", "enc-specific-friend",
  "enc-specific-pair", "enc-streak3-1", "enc-streak3-2", "enc-streak3-3", "enc-streak5-1", "enc-streak5-2",
  "enc-streak5-3", "enc-streak10-1", "enc-streak10-2", "enc-streak10-3", "enc-wrong-1", "enc-wrong-2",
  "enc-wrong-3", "equals", "feed-done", "feed-intro", "feed-next", "feed-nom",
  "feed-q-pre", "l1-intro-0-0-3", "l1-intro-0-0-4", "l1-intro-0-0-5", "l1-intro-0-0-6", "l1-intro-0-0-7",
  "l1-intro-0-0-8", "l1-intro-0-0-9", "l1-intro-0-0-10", "l1-intro-0-1-2", "l1-intro-0-1-3", "l1-intro-0-1-4",
  "l1-intro-0-1-5", "l1-intro-0-1-6", "l1-intro-0-1-7", "l1-intro-0-1-8", "l1-intro-0-1-9", "l1-intro-0-1-10",
  "l1-intro-0-2-1", "l1-intro-0-2-2", "l1-intro-0-2-3", "l1-intro-0-2-4", "l1-intro-0-2-5", "l1-intro-0-2-8",
  "l1-intro-0-2-10", "l1-intro-0-3-7", "l1-intro-0-3-10", "l1-intro-0-4-6", "l1-intro-0-4-10", "l1-intro-0-5-5",
  "l1-intro-0-5-10", "l1-intro-0-6-4", "l1-intro-0-7-3", "l1-intro-0-8-2", "l1-intro-0-9-1", "l1-intro-0-10-0",
  "l1-intro-0-10-1", "l1-intro-0-10-2", "l1-intro-0-10-3", "l1-intro-0-10-4", "l1-intro-0-10-5", "l1-intro-1-0-9",
  "l1-intro-1-0-10", "l1-intro-1-1-1", "l1-intro-1-1-2", "l1-intro-1-1-3", "l1-intro-1-1-4", "l1-intro-1-1-5",
  "l1-intro-1-1-6", "l1-intro-1-1-7", "l1-intro-1-1-8", "l1-intro-1-1-9", "l1-intro-1-2-1", "l1-intro-1-2-2",
  "l1-intro-1-2-3", "l1-intro-1-2-4", "l1-intro-1-2-5", "l1-intro-1-2-6", "l1-intro-1-2-7", "l1-intro-1-2-8",
  "l1-intro-1-2-9", "l1-intro-1-3-1", "l1-intro-1-3-2", "l1-intro-1-3-3", "l1-intro-1-3-4", "l1-intro-1-3-5",
  "l1-intro-1-3-6", "l1-intro-1-3-7", "l1-intro-1-3-9", "l1-intro-1-4-1", "l1-intro-1-4-2", "l1-intro-1-4-3",
  "l1-intro-1-4-4", "l1-intro-1-4-5", "l1-intro-1-4-6", "l1-intro-1-4-9", "l1-intro-1-5-1", "l1-intro-1-5-2",
  "l1-intro-1-5-3", "l1-intro-1-5-4", "l1-intro-1-5-5", "l1-intro-1-5-9", "l1-intro-1-6-1", "l1-intro-1-6-2",
  "l1-intro-1-6-3", "l1-intro-1-6-4", "l1-intro-1-6-9", "l1-intro-1-7-1", "l1-intro-1-7-2", "l1-intro-1-7-3",
  "l1-intro-1-7-9", "l1-intro-1-8-1", "l1-intro-1-8-2", "l1-intro-1-8-9", "l1-intro-1-9-0", "l1-intro-1-9-1",
  "l1-intro-1-9-2", "l1-intro-1-9-3", "l1-intro-1-9-4", "l1-intro-1-9-5", "l1-intro-1-9-6", "l1-intro-1-9-7",
  "l1-intro-1-9-8", "l1-intro-1-9-9", "l1-intro-1-10-0", "l1-intro-2-0-8", "l1-intro-2-0-10", "l1-intro-2-1-1",
  "l1-intro-2-1-2", "l1-intro-2-1-3", "l1-intro-2-1-4", "l1-intro-2-1-5", "l1-intro-2-1-6", "l1-intro-2-1-7",
  "l1-intro-2-1-8", "l1-intro-2-1-9", "l1-intro-2-2-1", "l1-intro-2-2-2", "l1-intro-2-2-3", "l1-intro-2-2-4",
  "l1-intro-2-2-5", "l1-intro-2-2-6", "l1-intro-2-2-8", "l1-intro-2-3-1", "l1-intro-2-3-2", "l1-intro-2-3-3",
  "l1-intro-2-3-4", "l1-intro-2-3-5", "l1-intro-2-3-7", "l1-intro-2-3-8", "l1-intro-2-4-1", "l1-intro-2-4-2",
  "l1-intro-2-4-3", "l1-intro-2-4-4", "l1-intro-2-4-6", "l1-intro-2-4-8", "l1-intro-2-5-1", "l1-intro-2-5-2",
  "l1-intro-2-5-3", "l1-intro-2-5-5", "l1-intro-2-5-8", "l1-intro-2-6-1", "l1-intro-2-6-2", "l1-intro-2-6-4",
  "l1-intro-2-6-8", "l1-intro-2-7-1", "l1-intro-2-7-3", "l1-intro-2-7-8", "l1-intro-2-8-0", "l1-intro-2-8-1",
  "l1-intro-2-8-2", "l1-intro-2-8-3", "l1-intro-2-8-4", "l1-intro-2-8-5", "l1-intro-2-8-6", "l1-intro-2-8-7",
  "l1-intro-2-8-8", "l1-intro-2-8-9", "l1-intro-2-9-1", "l1-intro-2-9-8", "l1-intro-2-10-0", "l1-intro-3-0-7",
  "l1-intro-3-0-10", "l1-intro-3-1-1", "l1-intro-3-1-2", "l1-intro-3-1-3", "l1-intro-3-1-4", "l1-intro-3-1-5",
  "l1-intro-3-1-6", "l1-intro-3-1-7", "l1-intro-3-1-9", "l1-intro-3-2-1", "l1-intro-3-2-2", "l1-intro-3-2-3",
  "l1-intro-3-2-4", "l1-intro-3-2-5", "l1-intro-3-2-7", "l1-intro-3-2-8", "l1-intro-3-3-1", "l1-intro-3-3-2",
  "l1-intro-3-3-3", "l1-intro-3-3-4", "l1-intro-3-3-7", "l1-intro-3-4-1", "l1-intro-3-4-2", "l1-intro-3-4-3",
  "l1-intro-3-4-6", "l1-intro-3-4-7", "l1-intro-3-5-1", "l1-intro-3-5-2", "l1-intro-3-5-5", "l1-intro-3-5-7",
  "l1-intro-3-6-1", "l1-intro-3-6-4", "l1-intro-3-6-7", "l1-intro-3-7-0", "l1-intro-3-7-1", "l1-intro-3-7-2",
  "l1-intro-3-7-3", "l1-intro-3-7-4", "l1-intro-3-7-5", "l1-intro-3-7-6", "l1-intro-3-7-7", "l1-intro-3-7-8",
  "l1-intro-3-7-9", "l1-intro-3-8-2", "l1-intro-3-8-7", "l1-intro-3-9-1", "l1-intro-3-9-7", "l1-intro-3-10-0",
  "l1-intro-4-0-6", "l1-intro-4-0-10", "l1-intro-4-1-1", "l1-intro-4-1-2", "l1-intro-4-1-3", "l1-intro-4-1-4",
  "l1-intro-4-1-5", "l1-intro-4-1-6", "l1-intro-4-1-9", "l1-intro-4-2-1", "l1-intro-4-2-2", "l1-intro-4-2-3",
  "l1-intro-4-2-4", "l1-intro-4-2-6", "l1-intro-4-2-8", "l1-intro-4-3-1", "l1-intro-4-3-2", "l1-intro-4-3-3",
  "l1-intro-4-3-6", "l1-intro-4-3-7", "l1-intro-4-4-1", "l1-intro-4-4-2", "l1-intro-4-4-6", "l1-intro-4-5-1",
  "l1-intro-4-5-5", "l1-intro-4-5-6", "l1-intro-4-6-0", "l1-intro-4-6-1", "l1-intro-4-6-2", "l1-intro-4-6-3",
  "l1-intro-4-6-4", "l1-intro-4-6-5", "l1-intro-4-6-6", "l1-intro-4-6-7", "l1-intro-4-6-8", "l1-intro-4-6-9",
  "l1-intro-4-7-3", "l1-intro-4-7-6", "l1-intro-4-8-2", "l1-intro-4-8-6", "l1-intro-4-9-1", "l1-intro-4-9-6",
  "l1-intro-4-10-0", "l1-intro-5-0-5", "l1-intro-5-0-10", "l1-intro-5-1-1", "l1-intro-5-1-2", "l1-intro-5-1-3",
  "l1-intro-5-1-4", "l1-intro-5-1-5", "l1-intro-5-1-9", "l1-intro-5-2-1", "l1-intro-5-2-2", "l1-intro-5-2-3",
  "l1-intro-5-2-5", "l1-intro-5-2-8", "l1-intro-5-3-1", "l1-intro-5-3-2", "l1-intro-5-3-5", "l1-intro-5-3-7",
  "l1-intro-5-4-1", "l1-intro-5-4-5", "l1-intro-5-4-6", "l1-intro-5-5-0", "l1-intro-5-5-1", "l1-intro-5-5-2",
  "l1-intro-5-5-3", "l1-intro-5-5-4", "l1-intro-5-5-5", "l1-intro-5-5-6", "l1-intro-5-5-7", "l1-intro-5-5-8",
  "l1-intro-5-5-9", "l1-intro-5-6-4", "l1-intro-5-6-5", "l1-intro-5-7-3", "l1-intro-5-7-5", "l1-intro-5-8-2",
  "l1-intro-5-8-5", "l1-intro-5-9-1", "l1-intro-5-9-5", "l1-intro-5-10-0", "l1-intro-6-0-4", "l1-intro-6-1-1",
  "l1-intro-6-1-2", "l1-intro-6-1-3", "l1-intro-6-1-4", "l1-intro-6-1-9", "l1-intro-6-2-1", "l1-intro-6-2-2",
  "l1-intro-6-2-4", "l1-intro-6-2-8", "l1-intro-6-3-1", "l1-intro-6-3-4", "l1-intro-6-3-7", "l1-intro-6-4-0",
  "l1-intro-6-4-1", "l1-intro-6-4-2", "l1-intro-6-4-3", "l1-intro-6-4-4", "l1-intro-6-4-5", "l1-intro-6-4-6",
  "l1-intro-6-4-7", "l1-intro-6-4-8", "l1-intro-6-4-9", "l1-intro-6-5-4", "l1-intro-6-5-5", "l1-intro-6-6-4",
  "l1-intro-6-7-3", "l1-intro-6-7-4", "l1-intro-6-8-2", "l1-intro-6-8-4", "l1-intro-6-9-1", "l1-intro-6-9-4",
  "l1-intro-7-0-3", "l1-intro-7-1-1", "l1-intro-7-1-2", "l1-intro-7-1-3", "l1-intro-7-1-9", "l1-intro-7-2-1",
  "l1-intro-7-2-3", "l1-intro-7-2-8", "l1-intro-7-3-0", "l1-intro-7-3-1", "l1-intro-7-3-2", "l1-intro-7-3-3",
  "l1-intro-7-3-4", "l1-intro-7-3-5", "l1-intro-7-3-6", "l1-intro-7-3-7", "l1-intro-7-3-8", "l1-intro-7-3-9",
  "l1-intro-7-4-3", "l1-intro-7-4-6", "l1-intro-7-5-3", "l1-intro-7-5-5", "l1-intro-7-6-3", "l1-intro-7-6-4",
  "l1-intro-7-7-3", "l1-intro-7-8-2", "l1-intro-7-8-3", "l1-intro-7-9-1", "l1-intro-7-9-3", "l1-intro-8-0-2",
  "l1-intro-8-1-1", "l1-intro-8-1-2", "l1-intro-8-1-9", "l1-intro-8-2-0", "l1-intro-8-2-1", "l1-intro-8-2-2",
  "l1-intro-8-2-3", "l1-intro-8-2-4", "l1-intro-8-2-5", "l1-intro-8-2-6", "l1-intro-8-2-7", "l1-intro-8-2-8",
  "l1-intro-8-2-9", "l1-intro-8-3-2", "l1-intro-8-3-7", "l1-intro-8-4-2", "l1-intro-8-4-6", "l1-intro-8-5-2",
  "l1-intro-8-5-5", "l1-intro-8-6-2", "l1-intro-8-6-4", "l1-intro-8-7-2", "l1-intro-8-7-3", "l1-intro-8-8-2",
  "l1-intro-8-9-1", "l1-intro-8-9-2", "l1-intro-9-0-1", "l1-intro-9-1-0", "l1-intro-9-1-1", "l1-intro-9-1-2",
  "l1-intro-9-1-3", "l1-intro-9-1-4", "l1-intro-9-1-5", "l1-intro-9-1-6", "l1-intro-9-1-7", "l1-intro-9-1-8",
  "l1-intro-9-1-9", "l1-intro-9-2-1", "l1-intro-9-2-8", "l1-intro-9-3-1", "l1-intro-9-3-7", "l1-intro-9-4-1",
  "l1-intro-9-4-6", "l1-intro-9-5-1", "l1-intro-9-5-5", "l1-intro-9-6-1", "l1-intro-9-6-4", "l1-intro-9-7-1",
  "l1-intro-9-7-3", "l1-intro-9-8-1", "l1-intro-9-8-2", "l1-intro-9-9-1", "l1-intro-10-0-0", "l1-intro-10-0-1",
  "l1-intro-10-0-2", "l1-intro-10-0-3", "l1-intro-10-0-4", "l1-intro-10-0-5", "l1-intro-10-1-0", "l1-intro-10-2-0",
  "l1-intro-10-3-0", "l1-intro-10-4-0", "l1-intro-10-5-0", "l1-intro-mt-1-1-9", "l1-intro-mt-1-2-8", "l1-intro-mt-1-2-9",
  "l1-intro-mt-1-3-7", "l1-intro-mt-1-3-9", "l1-intro-mt-1-4-6", "l1-intro-mt-1-4-9", "l1-intro-mt-1-5-5", "l1-intro-mt-1-5-9",
  "l1-intro-mt-1-6-4", "l1-intro-mt-1-6-9", "l1-intro-mt-1-7-3", "l1-intro-mt-1-7-9", "l1-intro-mt-1-8-2", "l1-intro-mt-1-8-9",
  "l1-intro-mt-1-9-1", "l1-intro-mt-1-9-2", "l1-intro-mt-1-9-3", "l1-intro-mt-1-9-4", "l1-intro-mt-1-9-5", "l1-intro-mt-1-9-6",
  "l1-intro-mt-1-9-7", "l1-intro-mt-1-9-8", "l1-intro-mt-1-9-9", "l1-intro-mt-2-1-8", "l1-intro-mt-2-1-9", "l1-intro-mt-2-2-8",
  "l1-intro-mt-2-3-7", "l1-intro-mt-2-3-8", "l1-intro-mt-2-4-6", "l1-intro-mt-2-4-8", "l1-intro-mt-2-5-5", "l1-intro-mt-2-5-8",
  "l1-intro-mt-2-6-4", "l1-intro-mt-2-6-8", "l1-intro-mt-2-7-3", "l1-intro-mt-2-7-8", "l1-intro-mt-2-8-1", "l1-intro-mt-2-8-2",
  "l1-intro-mt-2-8-3", "l1-intro-mt-2-8-4", "l1-intro-mt-2-8-5", "l1-intro-mt-2-8-6", "l1-intro-mt-2-8-7", "l1-intro-mt-2-8-8",
  "l1-intro-mt-2-8-9", "l1-intro-mt-2-9-1", "l1-intro-mt-2-9-8", "l1-intro-mt-3-1-7", "l1-intro-mt-3-1-9", "l1-intro-mt-3-2-7",
  "l1-intro-mt-3-2-8", "l1-intro-mt-3-3-7", "l1-intro-mt-3-4-6", "l1-intro-mt-3-4-7", "l1-intro-mt-3-5-5", "l1-intro-mt-3-5-7",
  "l1-intro-mt-3-6-4", "l1-intro-mt-3-6-7", "l1-intro-mt-3-7-1", "l1-intro-mt-3-7-2", "l1-intro-mt-3-7-3", "l1-intro-mt-3-7-4",
  "l1-intro-mt-3-7-5", "l1-intro-mt-3-7-6", "l1-intro-mt-3-7-7", "l1-intro-mt-3-7-8", "l1-intro-mt-3-7-9", "l1-intro-mt-3-8-2",
  "l1-intro-mt-3-8-7", "l1-intro-mt-3-9-1", "l1-intro-mt-3-9-7", "l1-intro-mt-4-1-6", "l1-intro-mt-4-1-9", "l1-intro-mt-4-2-6",
  "l1-intro-mt-4-2-8", "l1-intro-mt-4-3-6", "l1-intro-mt-4-3-7", "l1-intro-mt-4-4-6", "l1-intro-mt-4-5-5", "l1-intro-mt-4-5-6",
  "l1-intro-mt-4-6-1", "l1-intro-mt-4-6-2", "l1-intro-mt-4-6-3", "l1-intro-mt-4-6-4", "l1-intro-mt-4-6-5", "l1-intro-mt-4-6-6",
  "l1-intro-mt-4-6-7", "l1-intro-mt-4-6-8", "l1-intro-mt-4-6-9", "l1-intro-mt-4-7-3", "l1-intro-mt-4-7-6", "l1-intro-mt-4-8-2",
  "l1-intro-mt-4-8-6", "l1-intro-mt-4-9-1", "l1-intro-mt-4-9-6", "l1-intro-mt-5-1-5", "l1-intro-mt-5-1-9", "l1-intro-mt-5-2-5",
  "l1-intro-mt-5-2-8", "l1-intro-mt-5-3-5", "l1-intro-mt-5-3-7", "l1-intro-mt-5-4-5", "l1-intro-mt-5-4-6", "l1-intro-mt-5-5-1",
  "l1-intro-mt-5-5-2", "l1-intro-mt-5-5-3", "l1-intro-mt-5-5-4", "l1-intro-mt-5-5-5", "l1-intro-mt-5-5-6", "l1-intro-mt-5-5-7",
  "l1-intro-mt-5-5-8", "l1-intro-mt-5-5-9", "l1-intro-mt-5-6-4", "l1-intro-mt-5-6-5", "l1-intro-mt-5-7-3", "l1-intro-mt-5-7-5",
  "l1-intro-mt-5-8-2", "l1-intro-mt-5-8-5", "l1-intro-mt-5-9-1", "l1-intro-mt-5-9-5", "l1-intro-mt-6-1-4", "l1-intro-mt-6-1-9",
  "l1-intro-mt-6-2-4", "l1-intro-mt-6-2-8", "l1-intro-mt-6-3-4", "l1-intro-mt-6-3-7", "l1-intro-mt-6-4-1", "l1-intro-mt-6-4-2",
  "l1-intro-mt-6-4-3", "l1-intro-mt-6-4-4", "l1-intro-mt-6-4-5", "l1-intro-mt-6-4-6", "l1-intro-mt-6-4-7", "l1-intro-mt-6-4-8",
  "l1-intro-mt-6-4-9", "l1-intro-mt-6-5-4", "l1-intro-mt-6-5-5", "l1-intro-mt-6-6-4", "l1-intro-mt-6-7-3", "l1-intro-mt-6-7-4",
  "l1-intro-mt-6-8-2", "l1-intro-mt-6-8-4", "l1-intro-mt-6-9-1", "l1-intro-mt-6-9-4", "l1-intro-mt-7-1-3", "l1-intro-mt-7-1-9",
  "l1-intro-mt-7-2-3", "l1-intro-mt-7-2-8", "l1-intro-mt-7-3-1", "l1-intro-mt-7-3-2", "l1-intro-mt-7-3-3", "l1-intro-mt-7-3-4",
  "l1-intro-mt-7-3-5", "l1-intro-mt-7-3-6", "l1-intro-mt-7-3-7", "l1-intro-mt-7-3-8", "l1-intro-mt-7-3-9", "l1-intro-mt-7-4-3",
  "l1-intro-mt-7-4-6", "l1-intro-mt-7-5-3", "l1-intro-mt-7-5-5", "l1-intro-mt-7-6-3", "l1-intro-mt-7-6-4", "l1-intro-mt-7-7-3",
  "l1-intro-mt-7-8-2", "l1-intro-mt-7-8-3", "l1-intro-mt-7-9-1", "l1-intro-mt-7-9-3", "l1-intro-mt-8-1-2", "l1-intro-mt-8-1-9",
  "l1-intro-mt-8-2-1", "l1-intro-mt-8-2-2", "l1-intro-mt-8-2-3", "l1-intro-mt-8-2-4", "l1-intro-mt-8-2-5", "l1-intro-mt-8-2-6",
  "l1-intro-mt-8-2-7", "l1-intro-mt-8-2-8", "l1-intro-mt-8-2-9", "l1-intro-mt-8-3-2", "l1-intro-mt-8-3-7", "l1-intro-mt-8-4-2",
  "l1-intro-mt-8-4-6", "l1-intro-mt-8-5-2", "l1-intro-mt-8-5-5", "l1-intro-mt-8-6-2", "l1-intro-mt-8-6-4", "l1-intro-mt-8-7-2",
  "l1-intro-mt-8-7-3", "l1-intro-mt-8-8-2", "l1-intro-mt-8-9-1", "l1-intro-mt-8-9-2", "l1-intro-mt-9-1-1", "l1-intro-mt-9-1-2",
  "l1-intro-mt-9-1-3", "l1-intro-mt-9-1-4", "l1-intro-mt-9-1-5", "l1-intro-mt-9-1-6", "l1-intro-mt-9-1-7", "l1-intro-mt-9-1-8",
  "l1-intro-mt-9-1-9", "l1-intro-mt-9-2-1", "l1-intro-mt-9-2-8", "l1-intro-mt-9-3-1", "l1-intro-mt-9-3-7", "l1-intro-mt-9-4-1",
  "l1-intro-mt-9-4-6", "l1-intro-mt-9-5-1", "l1-intro-mt-9-5-5", "l1-intro-mt-9-6-1", "l1-intro-mt-9-6-4", "l1-intro-mt-9-7-1",
  "l1-intro-mt-9-7-3", "l1-intro-mt-9-8-1", "l1-intro-mt-9-8-2", "l1-intro-mt-9-9-1", "l1-rwd-0-0-3-3", "l1-rwd-0-0-4-4",
  "l1-rwd-0-0-5-5", "l1-rwd-0-0-6-6", "l1-rwd-0-0-7-7", "l1-rwd-0-0-8-8", "l1-rwd-0-0-9-9", "l1-rwd-0-0-10-10",
  "l1-rwd-0-1-2-3", "l1-rwd-0-1-3-4", "l1-rwd-0-1-4-5", "l1-rwd-0-1-5-6", "l1-rwd-0-1-6-7", "l1-rwd-0-1-7-8",
  "l1-rwd-0-1-8-9", "l1-rwd-0-1-9-10", "l1-rwd-0-1-10-11", "l1-rwd-0-2-1-3", "l1-rwd-0-2-2-4", "l1-rwd-0-2-3-5",
  "l1-rwd-0-2-4-6", "l1-rwd-0-2-5-7", "l1-rwd-0-2-8-10", "l1-rwd-0-2-10-12", "l1-rwd-0-3-7-10", "l1-rwd-0-3-10-13",
  "l1-rwd-0-4-6-10", "l1-rwd-0-4-10-14", "l1-rwd-0-5-5-10", "l1-rwd-0-5-10-15", "l1-rwd-0-6-4-10", "l1-rwd-0-7-3-10",
  "l1-rwd-0-8-2-10", "l1-rwd-0-9-1-10", "l1-rwd-0-10-0-10", "l1-rwd-0-10-1-11", "l1-rwd-0-10-2-12", "l1-rwd-0-10-3-13",
  "l1-rwd-0-10-4-14", "l1-rwd-0-10-5-15", "l1-rwd-1-0-9-10", "l1-rwd-1-0-10-11", "l1-rwd-1-1-1-3", "l1-rwd-1-1-2-4",
  "l1-rwd-1-1-3-5", "l1-rwd-1-1-4-6", "l1-rwd-1-1-5-7", "l1-rwd-1-1-6-8", "l1-rwd-1-1-7-9", "l1-rwd-1-1-8-10",
  "l1-rwd-1-1-9-11", "l1-rwd-1-2-1-4", "l1-rwd-1-2-2-5", "l1-rwd-1-2-3-6", "l1-rwd-1-2-4-7", "l1-rwd-1-2-5-8",
  "l1-rwd-1-2-6-9", "l1-rwd-1-2-7-10", "l1-rwd-1-2-8-11", "l1-rwd-1-2-9-12", "l1-rwd-1-3-1-5", "l1-rwd-1-3-2-6",
  "l1-rwd-1-3-3-7", "l1-rwd-1-3-4-8", "l1-rwd-1-3-5-9", "l1-rwd-1-3-6-10", "l1-rwd-1-3-7-11", "l1-rwd-1-3-9-13",
  "l1-rwd-1-4-1-6", "l1-rwd-1-4-2-7", "l1-rwd-1-4-3-8", "l1-rwd-1-4-4-9", "l1-rwd-1-4-5-10", "l1-rwd-1-4-6-11",
  "l1-rwd-1-4-9-14", "l1-rwd-1-5-1-7", "l1-rwd-1-5-2-8", "l1-rwd-1-5-3-9", "l1-rwd-1-5-4-10", "l1-rwd-1-5-5-11",
  "l1-rwd-1-5-9-15", "l1-rwd-1-6-1-8", "l1-rwd-1-6-2-9", "l1-rwd-1-6-3-10", "l1-rwd-1-6-4-11", "l1-rwd-1-6-9-16",
  "l1-rwd-1-7-1-9", "l1-rwd-1-7-2-10", "l1-rwd-1-7-3-11", "l1-rwd-1-7-9-17", "l1-rwd-1-8-1-10", "l1-rwd-1-8-2-11",
  "l1-rwd-1-8-9-18", "l1-rwd-1-9-0-10", "l1-rwd-1-9-1-11", "l1-rwd-1-9-2-12", "l1-rwd-1-9-3-13", "l1-rwd-1-9-4-14",
  "l1-rwd-1-9-5-15", "l1-rwd-1-9-6-16", "l1-rwd-1-9-7-17", "l1-rwd-1-9-8-18", "l1-rwd-1-9-9-19", "l1-rwd-1-10-0-11",
  "l1-rwd-2-0-8-10", "l1-rwd-2-0-10-12", "l1-rwd-2-1-1-4", "l1-rwd-2-1-2-5", "l1-rwd-2-1-3-6", "l1-rwd-2-1-4-7",
  "l1-rwd-2-1-5-8", "l1-rwd-2-1-6-9", "l1-rwd-2-1-7-10", "l1-rwd-2-1-8-11", "l1-rwd-2-1-9-12", "l1-rwd-2-2-1-5",
  "l1-rwd-2-2-2-6", "l1-rwd-2-2-3-7", "l1-rwd-2-2-4-8", "l1-rwd-2-2-5-9", "l1-rwd-2-2-6-10", "l1-rwd-2-2-8-12",
  "l1-rwd-2-3-1-6", "l1-rwd-2-3-2-7", "l1-rwd-2-3-3-8", "l1-rwd-2-3-4-9", "l1-rwd-2-3-5-10", "l1-rwd-2-3-7-12",
  "l1-rwd-2-3-8-13", "l1-rwd-2-4-1-7", "l1-rwd-2-4-2-8", "l1-rwd-2-4-3-9", "l1-rwd-2-4-4-10", "l1-rwd-2-4-6-12",
  "l1-rwd-2-4-8-14", "l1-rwd-2-5-1-8", "l1-rwd-2-5-2-9", "l1-rwd-2-5-3-10", "l1-rwd-2-5-5-12", "l1-rwd-2-5-8-15",
  "l1-rwd-2-6-1-9", "l1-rwd-2-6-2-10", "l1-rwd-2-6-4-12", "l1-rwd-2-6-8-16", "l1-rwd-2-7-1-10", "l1-rwd-2-7-3-12",
  "l1-rwd-2-7-8-17", "l1-rwd-2-8-0-10", "l1-rwd-2-8-1-11", "l1-rwd-2-8-2-12", "l1-rwd-2-8-3-13", "l1-rwd-2-8-4-14",
  "l1-rwd-2-8-5-15", "l1-rwd-2-8-6-16", "l1-rwd-2-8-7-17", "l1-rwd-2-8-8-18", "l1-rwd-2-8-9-19", "l1-rwd-2-9-1-12",
  "l1-rwd-2-9-8-19", "l1-rwd-2-10-0-12", "l1-rwd-3-0-7-10", "l1-rwd-3-0-10-13", "l1-rwd-3-1-1-5", "l1-rwd-3-1-2-6",
  "l1-rwd-3-1-3-7", "l1-rwd-3-1-4-8", "l1-rwd-3-1-5-9", "l1-rwd-3-1-6-10", "l1-rwd-3-1-7-11", "l1-rwd-3-1-9-13",
  "l1-rwd-3-2-1-6", "l1-rwd-3-2-2-7", "l1-rwd-3-2-3-8", "l1-rwd-3-2-4-9", "l1-rwd-3-2-5-10", "l1-rwd-3-2-7-12",
  "l1-rwd-3-2-8-13", "l1-rwd-3-3-1-7", "l1-rwd-3-3-2-8", "l1-rwd-3-3-3-9", "l1-rwd-3-3-4-10", "l1-rwd-3-3-7-13",
  "l1-rwd-3-4-1-8", "l1-rwd-3-4-2-9", "l1-rwd-3-4-3-10", "l1-rwd-3-4-6-13", "l1-rwd-3-4-7-14", "l1-rwd-3-5-1-9",
  "l1-rwd-3-5-2-10", "l1-rwd-3-5-5-13", "l1-rwd-3-5-7-15", "l1-rwd-3-6-1-10", "l1-rwd-3-6-4-13", "l1-rwd-3-6-7-16",
  "l1-rwd-3-7-0-10", "l1-rwd-3-7-1-11", "l1-rwd-3-7-2-12", "l1-rwd-3-7-3-13", "l1-rwd-3-7-4-14", "l1-rwd-3-7-5-15",
  "l1-rwd-3-7-6-16", "l1-rwd-3-7-7-17", "l1-rwd-3-7-8-18", "l1-rwd-3-7-9-19", "l1-rwd-3-8-2-13", "l1-rwd-3-8-7-18",
  "l1-rwd-3-9-1-13", "l1-rwd-3-9-7-19", "l1-rwd-3-10-0-13", "l1-rwd-4-0-6-10", "l1-rwd-4-0-10-14", "l1-rwd-4-1-1-6",
  "l1-rwd-4-1-2-7", "l1-rwd-4-1-3-8", "l1-rwd-4-1-4-9", "l1-rwd-4-1-5-10", "l1-rwd-4-1-6-11", "l1-rwd-4-1-9-14",
  "l1-rwd-4-2-1-7", "l1-rwd-4-2-2-8", "l1-rwd-4-2-3-9", "l1-rwd-4-2-4-10", "l1-rwd-4-2-6-12", "l1-rwd-4-2-8-14",
  "l1-rwd-4-3-1-8", "l1-rwd-4-3-2-9", "l1-rwd-4-3-3-10", "l1-rwd-4-3-6-13", "l1-rwd-4-3-7-14", "l1-rwd-4-4-1-9",
  "l1-rwd-4-4-2-10", "l1-rwd-4-4-6-14", "l1-rwd-4-5-1-10", "l1-rwd-4-5-5-14", "l1-rwd-4-5-6-15", "l1-rwd-4-6-0-10",
  "l1-rwd-4-6-1-11", "l1-rwd-4-6-2-12", "l1-rwd-4-6-3-13", "l1-rwd-4-6-4-14", "l1-rwd-4-6-5-15", "l1-rwd-4-6-6-16",
  "l1-rwd-4-6-7-17", "l1-rwd-4-6-8-18", "l1-rwd-4-6-9-19", "l1-rwd-4-7-3-14", "l1-rwd-4-7-6-17", "l1-rwd-4-8-2-14",
  "l1-rwd-4-8-6-18", "l1-rwd-4-9-1-14", "l1-rwd-4-9-6-19", "l1-rwd-4-10-0-14", "l1-rwd-5-0-5-10", "l1-rwd-5-0-10-15",
  "l1-rwd-5-1-1-7", "l1-rwd-5-1-2-8", "l1-rwd-5-1-3-9", "l1-rwd-5-1-4-10", "l1-rwd-5-1-5-11", "l1-rwd-5-1-9-15",
  "l1-rwd-5-2-1-8", "l1-rwd-5-2-2-9", "l1-rwd-5-2-3-10", "l1-rwd-5-2-5-12", "l1-rwd-5-2-8-15", "l1-rwd-5-3-1-9",
  "l1-rwd-5-3-2-10", "l1-rwd-5-3-5-13", "l1-rwd-5-3-7-15", "l1-rwd-5-4-1-10", "l1-rwd-5-4-5-14", "l1-rwd-5-4-6-15",
  "l1-rwd-5-5-0-10", "l1-rwd-5-5-1-11", "l1-rwd-5-5-2-12", "l1-rwd-5-5-3-13", "l1-rwd-5-5-4-14", "l1-rwd-5-5-5-15",
  "l1-rwd-5-5-6-16", "l1-rwd-5-5-7-17", "l1-rwd-5-5-8-18", "l1-rwd-5-5-9-19", "l1-rwd-5-6-4-15", "l1-rwd-5-6-5-16",
  "l1-rwd-5-7-3-15", "l1-rwd-5-7-5-17", "l1-rwd-5-8-2-15", "l1-rwd-5-8-5-18", "l1-rwd-5-9-1-15", "l1-rwd-5-9-5-19",
  "l1-rwd-5-10-0-15", "l1-rwd-6-0-4-10", "l1-rwd-6-1-1-8", "l1-rwd-6-1-2-9", "l1-rwd-6-1-3-10", "l1-rwd-6-1-4-11",
  "l1-rwd-6-1-9-16", "l1-rwd-6-2-1-9", "l1-rwd-6-2-2-10", "l1-rwd-6-2-4-12", "l1-rwd-6-2-8-16", "l1-rwd-6-3-1-10",
  "l1-rwd-6-3-4-13", "l1-rwd-6-3-7-16", "l1-rwd-6-4-0-10", "l1-rwd-6-4-1-11", "l1-rwd-6-4-2-12", "l1-rwd-6-4-3-13",
  "l1-rwd-6-4-4-14", "l1-rwd-6-4-5-15", "l1-rwd-6-4-6-16", "l1-rwd-6-4-7-17", "l1-rwd-6-4-8-18", "l1-rwd-6-4-9-19",
  "l1-rwd-6-5-4-15", "l1-rwd-6-5-5-16", "l1-rwd-6-6-4-16", "l1-rwd-6-7-3-16", "l1-rwd-6-7-4-17", "l1-rwd-6-8-2-16",
  "l1-rwd-6-8-4-18", "l1-rwd-6-9-1-16", "l1-rwd-6-9-4-19", "l1-rwd-7-0-3-10", "l1-rwd-7-1-1-9", "l1-rwd-7-1-2-10",
  "l1-rwd-7-1-3-11", "l1-rwd-7-1-9-17", "l1-rwd-7-2-1-10", "l1-rwd-7-2-3-12", "l1-rwd-7-2-8-17", "l1-rwd-7-3-0-10",
  "l1-rwd-7-3-1-11", "l1-rwd-7-3-2-12", "l1-rwd-7-3-3-13", "l1-rwd-7-3-4-14", "l1-rwd-7-3-5-15", "l1-rwd-7-3-6-16",
  "l1-rwd-7-3-7-17", "l1-rwd-7-3-8-18", "l1-rwd-7-3-9-19", "l1-rwd-7-4-3-14", "l1-rwd-7-4-6-17", "l1-rwd-7-5-3-15",
  "l1-rwd-7-5-5-17", "l1-rwd-7-6-3-16", "l1-rwd-7-6-4-17", "l1-rwd-7-7-3-17", "l1-rwd-7-8-2-17", "l1-rwd-7-8-3-18",
  "l1-rwd-7-9-1-17", "l1-rwd-7-9-3-19", "l1-rwd-8-0-2-10", "l1-rwd-8-1-1-10", "l1-rwd-8-1-2-11", "l1-rwd-8-1-9-18",
  "l1-rwd-8-2-0-10", "l1-rwd-8-2-1-11", "l1-rwd-8-2-2-12", "l1-rwd-8-2-3-13", "l1-rwd-8-2-4-14", "l1-rwd-8-2-5-15",
  "l1-rwd-8-2-6-16", "l1-rwd-8-2-7-17", "l1-rwd-8-2-8-18", "l1-rwd-8-2-9-19", "l1-rwd-8-3-2-13", "l1-rwd-8-3-7-18",
  "l1-rwd-8-4-2-14", "l1-rwd-8-4-6-18", "l1-rwd-8-5-2-15", "l1-rwd-8-5-5-18", "l1-rwd-8-6-2-16", "l1-rwd-8-6-4-18",
  "l1-rwd-8-7-2-17", "l1-rwd-8-7-3-18", "l1-rwd-8-8-2-18", "l1-rwd-8-9-1-18", "l1-rwd-8-9-2-19", "l1-rwd-9-0-1-10",
  "l1-rwd-9-1-0-10", "l1-rwd-9-1-1-11", "l1-rwd-9-1-2-12", "l1-rwd-9-1-3-13", "l1-rwd-9-1-4-14", "l1-rwd-9-1-5-15",
  "l1-rwd-9-1-6-16", "l1-rwd-9-1-7-17", "l1-rwd-9-1-8-18", "l1-rwd-9-1-9-19", "l1-rwd-9-2-1-12", "l1-rwd-9-2-8-19",
  "l1-rwd-9-3-1-13", "l1-rwd-9-3-7-19", "l1-rwd-9-4-1-14", "l1-rwd-9-4-6-19", "l1-rwd-9-5-1-15", "l1-rwd-9-5-5-19",
  "l1-rwd-9-6-1-16", "l1-rwd-9-6-4-19", "l1-rwd-9-7-1-17", "l1-rwd-9-7-3-19", "l1-rwd-9-8-1-18", "l1-rwd-9-8-2-19",
  "l1-rwd-9-9-1-19", "l1-rwd-10-0-0-10", "l1-rwd-10-0-1-11", "l1-rwd-10-0-2-12", "l1-rwd-10-0-3-13", "l1-rwd-10-0-4-14",
  "l1-rwd-10-0-5-15", "l1-rwd-10-1-0-11", "l1-rwd-10-2-0-12", "l1-rwd-10-3-0-13", "l1-rwd-10-4-0-14", "l1-rwd-10-5-0-15",
  "l1-step2-0-3", "l1-step2-0-4", "l1-step2-0-5", "l1-step2-0-6", "l1-step2-0-7", "l1-step2-0-8",
  "l1-step2-0-9", "l1-step2-1-2", "l1-step2-1-3", "l1-step2-1-4", "l1-step2-1-5", "l1-step2-1-6",
  "l1-step2-1-7", "l1-step2-1-8", "l1-step2-1-10", "l1-step2-2-1", "l1-step2-2-2", "l1-step2-2-3",
  "l1-step2-2-4", "l1-step2-2-5", "l1-step2-2-6", "l1-step2-2-7", "l1-step2-2-8", "l1-step2-2-10",
  "l1-step2-3-1", "l1-step2-3-2", "l1-step2-3-3", "l1-step2-3-4", "l1-step2-3-5", "l1-step2-3-6",
  "l1-step2-3-7", "l1-step2-3-10", "l1-step2-4-1", "l1-step2-4-2", "l1-step2-4-3", "l1-step2-4-4",
  "l1-step2-4-5", "l1-step2-4-6", "l1-step2-4-10", "l1-step2-5-1", "l1-step2-5-2", "l1-step2-5-3",
  "l1-step2-5-4", "l1-step2-5-5", "l1-step2-5-10", "l1-step2-6-1", "l1-step2-6-2", "l1-step2-6-3",
  "l1-step2-6-4", "l1-step2-6-10", "l1-step2-7-1", "l1-step2-7-2", "l1-step2-7-3", "l1-step2-7-10",
  "l1-step2-8-1", "l1-step2-8-2", "l1-step2-8-10", "l1-step2-9-1", "l1-step2-9-10", "l1-step2-10-0",
  "l1-step2-10-1", "l1-step2-10-2", "l1-step2-10-3", "l1-step2-10-4", "l1-step2-10-5", "l1-step2-10-6",
  "l1-step2-10-7", "l1-step2-10-8", "l1-step2-10-9", "l1-sub-0-0", "l1-sub-0-1", "l1-sub-0-2",
  "l1-sub-0-10", "l1-sub-1-1", "l1-sub-1-2", "l1-sub-1-3", "l1-sub-1-4", "l1-sub-1-5",
  "l1-sub-1-6", "l1-sub-1-7", "l1-sub-1-8", "l1-sub-1-9", "l1-sub-2-1", "l1-sub-2-2",
  "l1-sub-2-3", "l1-sub-2-4", "l1-sub-2-5", "l1-sub-2-6", "l1-sub-2-7", "l1-sub-2-8",
  "l1-sub-3-1", "l1-sub-3-2", "l1-sub-3-3", "l1-sub-3-4", "l1-sub-3-5", "l1-sub-3-6",
  "l1-sub-3-7", "l1-sub-4-1", "l1-sub-4-2", "l1-sub-4-3", "l1-sub-4-4", "l1-sub-4-5",
  "l1-sub-4-6", "l1-sub-5-1", "l1-sub-5-2", "l1-sub-5-3", "l1-sub-5-4", "l1-sub-5-5",
  "l1-sub-6-1", "l1-sub-6-2", "l1-sub-6-3", "l1-sub-6-4", "l1-sub-7-1", "l1-sub-7-2",
  "l1-sub-7-3", "l1-sub-8-1", "l1-sub-8-2", "l1-sub-9-1", "l1-sub-10-0", "l1-sub-find-ten",
  "l2-cmp-2-9", "l2-cmp-3-8", "l2-cmp-3-9", "l2-cmp-4-7", "l2-cmp-4-8", "l2-cmp-4-9",
  "l2-cmp-5-6", "l2-cmp-5-7", "l2-cmp-5-8", "l2-cmp-5-9", "l2-cmp-6-5", "l2-cmp-6-7",
  "l2-cmp-6-8", "l2-cmp-6-9", "l2-cmp-7-4", "l2-cmp-7-5", "l2-cmp-7-6", "l2-cmp-7-8",
  "l2-cmp-7-9", "l2-cmp-8-3", "l2-cmp-8-4", "l2-cmp-8-5", "l2-cmp-8-6", "l2-cmp-8-7",
  "l2-cmp-8-9", "l2-cmp-9-2", "l2-cmp-9-3", "l2-cmp-9-4", "l2-cmp-9-5", "l2-cmp-9-6",
  "l2-cmp-9-7", "l2-cmp-9-8", "l2-rwd-0-0-0", "l2-rwd-1-0-1", "l2-rwd-1-1-2", "l2-rwd-1-2-3",
  "l2-rwd-1-3-4", "l2-rwd-1-4-5", "l2-rwd-1-5-6", "l2-rwd-1-6-7", "l2-rwd-1-7-8", "l2-rwd-1-8-9",
  "l2-rwd-1-9-10", "l2-rwd-1-10-11", "l2-rwd-2-0-2", "l2-rwd-2-1-3", "l2-rwd-2-2-4", "l2-rwd-2-3-5",
  "l2-rwd-2-4-6", "l2-rwd-2-5-7", "l2-rwd-2-6-8", "l2-rwd-2-7-9", "l2-rwd-2-8-10", "l2-rwd-2-9-11",
  "l2-rwd-2-10-12", "l2-rwd-3-0-3", "l2-rwd-3-1-4", "l2-rwd-3-2-5", "l2-rwd-3-3-6", "l2-rwd-3-4-7",
  "l2-rwd-3-5-8", "l2-rwd-3-6-9", "l2-rwd-3-7-10", "l2-rwd-3-8-11", "l2-rwd-3-9-12", "l2-rwd-3-10-13",
  "l2-rwd-4-0-4", "l2-rwd-4-1-5", "l2-rwd-4-2-6", "l2-rwd-4-3-7", "l2-rwd-4-4-8", "l2-rwd-4-5-9",
  "l2-rwd-4-6-10", "l2-rwd-4-7-11", "l2-rwd-4-8-12", "l2-rwd-4-9-13", "l2-rwd-4-10-14", "l2-rwd-5-0-5",
  "l2-rwd-5-1-6", "l2-rwd-5-2-7", "l2-rwd-5-3-8", "l2-rwd-5-4-9", "l2-rwd-5-5-10", "l2-rwd-5-6-11",
  "l2-rwd-5-7-12", "l2-rwd-5-8-13", "l2-rwd-5-9-14", "l2-rwd-5-10-15", "l2-rwd-6-0-6", "l2-rwd-6-1-7",
  "l2-rwd-6-2-8", "l2-rwd-6-3-9", "l2-rwd-6-4-10", "l2-rwd-6-5-11", "l2-rwd-6-6-12", "l2-rwd-6-7-13",
  "l2-rwd-6-8-14", "l2-rwd-6-9-15", "l2-rwd-6-10-16", "l2-rwd-7-0-7", "l2-rwd-7-1-8", "l2-rwd-7-2-9",
  "l2-rwd-7-3-10", "l2-rwd-7-4-11", "l2-rwd-7-5-12", "l2-rwd-7-6-13", "l2-rwd-7-7-14", "l2-rwd-7-8-15",
  "l2-rwd-7-9-16", "l2-rwd-7-10-17", "l2-rwd-8-0-8", "l2-rwd-8-1-9", "l2-rwd-8-2-10", "l2-rwd-8-3-11",
  "l2-rwd-8-4-12", "l2-rwd-8-5-13", "l2-rwd-8-6-14", "l2-rwd-8-7-15", "l2-rwd-8-8-16", "l2-rwd-8-9-17",
  "l2-rwd-8-10-18", "l2-rwd-9-0-9", "l2-rwd-9-1-10", "l2-rwd-9-2-11", "l2-rwd-9-3-12", "l2-rwd-9-4-13",
  "l2-rwd-9-5-14", "l2-rwd-9-6-15", "l2-rwd-9-7-16", "l2-rwd-9-8-17", "l2-rwd-9-9-18", "l2-rwd-9-10-19",
  "l2-rwd-10-0-10", "l2-rwd-10-1-11", "l2-rwd-10-2-12", "l2-rwd-10-3-13", "l2-rwd-10-4-14", "l2-rwd-10-5-15",
  "l2-rwd-10-6-16", "l2-rwd-10-7-17", "l2-rwd-10-8-18", "l2-rwd-10-9-19", "l2-rwd-11-1-12", "l2-rwd-11-2-13",
  "l2-rwd-11-3-14", "l2-rwd-11-4-15", "l2-rwd-11-5-16", "l2-rwd-11-6-17", "l2-rwd-11-7-18", "l2-rwd-11-8-19",
  "l2-rwd-11-9-20", "l2-rwd-12-1-13", "l2-rwd-12-2-14", "l2-rwd-12-3-15", "l2-rwd-12-4-16", "l2-rwd-12-5-17",
  "l2-rwd-12-6-18", "l2-rwd-12-7-19", "l2-rwd-12-8-20", "l2-rwd-12-9-21", "l2-rwd-13-1-14", "l2-rwd-13-2-15",
  "l2-rwd-13-3-16", "l2-rwd-13-4-17", "l2-rwd-13-5-18", "l2-rwd-13-6-19", "l2-rwd-13-7-20", "l2-rwd-13-8-21",
  "l2-rwd-13-9-22", "l2-rwd-14-1-15", "l2-rwd-14-2-16", "l2-rwd-14-3-17", "l2-rwd-14-4-18", "l2-rwd-14-5-19",
  "l2-rwd-14-6-20", "l2-rwd-14-7-21", "l2-rwd-14-8-22", "l2-rwd-14-9-23", "l2-rwd-15-1-16", "l2-rwd-15-2-17",
  "l2-rwd-15-3-18", "l2-rwd-15-4-19", "l2-rwd-15-5-20", "l2-rwd-15-6-21", "l2-rwd-15-7-22", "l2-rwd-15-8-23",
  "l2-rwd-15-9-24", "l2-rwd-16-1-17", "l2-rwd-16-2-18", "l2-rwd-16-3-19", "l2-rwd-16-4-20", "l2-rwd-16-5-21",
  "l2-rwd-16-6-22", "l2-rwd-16-7-23", "l2-rwd-16-8-24", "l2-rwd-16-9-25", "l2-rwd-17-1-18", "l2-rwd-17-2-19",
  "l2-rwd-17-3-20", "l2-rwd-17-4-21", "l2-rwd-17-5-22", "l2-rwd-17-6-23", "l2-rwd-17-7-24", "l2-rwd-17-8-25",
  "l2-rwd-17-9-26", "l2-rwd-18-1-19", "l2-rwd-18-2-20", "l2-rwd-18-3-21", "l2-rwd-18-4-22", "l2-rwd-18-5-23",
  "l2-rwd-18-6-24", "l2-rwd-18-7-25", "l2-rwd-18-8-26", "l2-rwd-18-9-27", "l2-rwd-19-1-20", "l2-rwd-19-2-21",
  "l2-rwd-19-3-22", "l2-rwd-19-4-23", "l2-rwd-19-5-24", "l2-rwd-19-6-25", "l2-rwd-19-7-26", "l2-rwd-19-8-27",
  "l2-rwd-19-9-28", "l2-rwd-20-1-21", "l2-rwd-20-2-22", "l2-rwd-20-3-23", "l2-rwd-20-4-24", "l2-rwd-20-5-25",
  "l2-rwd-20-6-26", "l2-rwd-20-7-27", "l2-rwd-20-8-28", "l2-rwd-20-9-29", "l2-s1-1-9", "l2-s1-1-10",
  "l2-s1-2-8", "l2-s1-2-9", "l2-s1-2-10", "l2-s1-3-7", "l2-s1-3-8", "l2-s1-3-9",
  "l2-s1-3-10", "l2-s1-4-6", "l2-s1-4-7", "l2-s1-4-8", "l2-s1-4-9", "l2-s1-4-10",
  "l2-s1-5-5", "l2-s1-5-6", "l2-s1-5-7", "l2-s1-5-8", "l2-s1-5-9", "l2-s1-5-10",
  "l2-s1-6-4", "l2-s1-6-5", "l2-s1-6-6", "l2-s1-6-7", "l2-s1-6-8", "l2-s1-6-9",
  "l2-s1-6-10", "l2-s1-7-3", "l2-s1-7-4", "l2-s1-7-5", "l2-s1-7-6", "l2-s1-7-7",
  "l2-s1-7-8", "l2-s1-7-9", "l2-s1-7-10", "l2-s1-8-2", "l2-s1-8-3", "l2-s1-8-4",
  "l2-s1-8-5", "l2-s1-8-6", "l2-s1-8-7", "l2-s1-8-8", "l2-s1-8-9", "l2-s1-8-10",
  "l2-s1-9-1", "l2-s1-9-2", "l2-s1-9-3", "l2-s1-9-4", "l2-s1-9-5", "l2-s1-9-6",
  "l2-s1-9-7", "l2-s1-9-8", "l2-s1-9-9", "l2-s1-9-10", "l2-s1-10-1", "l2-s1-10-2",
  "l2-s1-10-3", "l2-s1-10-4", "l2-s1-10-5", "l2-s1-10-6", "l2-s1-10-7", "l2-s1-10-8",
  "l2-s1-10-9", "l2-s2-5", "l2-s2-6", "l2-s2-7", "l2-s2-8", "l2-s2-9",
  "l2-s2-10", "l2-s3-1-0", "l2-s3-1-1", "l2-s3-2-0", "l2-s3-2-1", "l2-s3-2-2",
  "l2-s3-3-0", "l2-s3-3-1", "l2-s3-3-2", "l2-s3-3-3", "l2-s3-4-0", "l2-s3-4-1",
  "l2-s3-4-2", "l2-s3-4-3", "l2-s3-4-4", "l2-s3-5-0", "l2-s3-5-1", "l2-s3-5-2",
  "l2-s3-5-3", "l2-s3-5-4", "l2-s3-5-5", "l2-s3-6-0", "l2-s3-6-1", "l2-s3-6-2",
  "l2-s3-6-3", "l2-s3-6-4", "l2-s3-7-0", "l2-s3-7-1", "l2-s3-7-2", "l2-s3-7-3",
  "l2-s3-8-0", "l2-s3-8-1", "l2-s3-8-2", "l2-s3-9-0", "l2-s3-9-1", "l2-s4-1-0-1-10",
  "l2-s4-1-1-0-9", "l2-s4-2-0-2-10", "l2-s4-2-1-1-9", "l2-s4-2-2-0-8", "l2-s4-3-0-3-10", "l2-s4-3-1-2-9",
  "l2-s4-3-2-1-8", "l2-s4-3-3-0-7", "l2-s4-4-0-4-10", "l2-s4-4-1-3-9", "l2-s4-4-2-2-8", "l2-s4-4-3-1-7",
  "l2-s4-4-4-0-6", "l2-s4-5-0-5-10", "l2-s4-5-1-4-9", "l2-s4-5-2-3-8", "l2-s4-5-3-2-7", "l2-s4-5-4-1-6",
  "l2-s4-5-5-0-5", "l2-s4-6-0-6-10", "l2-s4-6-1-5-9", "l2-s4-6-2-4-8", "l2-s4-6-3-3-7", "l2-s4-6-4-2-6",
  "l2-s4-7-0-7-10", "l2-s4-7-1-6-9", "l2-s4-7-2-5-8", "l2-s4-7-3-4-7", "l2-s4-8-0-8-10", "l2-s4-8-1-7-9",
  "l2-s4-8-2-6-8", "l2-s4-9-0-9-10", "l2-s4-9-1-8-9", "l2-s4s-2-9-1-1-9", "l2-s4s-3-8-2-1-8", "l2-s4s-3-9-1-2-9",
  "l2-s4s-4-7-3-1-7", "l2-s4s-4-8-2-2-8", "l2-s4s-4-9-1-3-9", "l2-s4s-5-6-4-1-6", "l2-s4s-5-7-3-2-7", "l2-s4s-5-8-2-3-8",
  "l2-s4s-5-9-1-4-9", "l2-s4s-6-7-3-3-7", "l2-s4s-6-8-2-4-8", "l2-s4s-6-9-1-5-9", "l2-s4s-7-8-2-5-8", "l2-s4s-7-9-1-6-9",
  "l2-s4s-8-9-1-7-9", "l2-simple-0-0", "l2-simple-1-0", "l2-simple-1-1", "l2-simple-1-2", "l2-simple-1-3",
  "l2-simple-1-4", "l2-simple-1-5", "l2-simple-1-6", "l2-simple-1-7", "l2-simple-1-8", "l2-simple-2-0",
  "l2-simple-2-1", "l2-simple-2-2", "l2-simple-2-3", "l2-simple-2-4", "l2-simple-2-5", "l2-simple-2-6",
  "l2-simple-2-7", "l2-simple-3-0", "l2-simple-3-1", "l2-simple-3-2", "l2-simple-3-3", "l2-simple-3-4",
  "l2-simple-3-5", "l2-simple-3-6", "l2-simple-4-0", "l2-simple-4-1", "l2-simple-4-2", "l2-simple-4-3",
  "l2-simple-4-4", "l2-simple-4-5", "l2-simple-5-0", "l2-simple-5-1", "l2-simple-5-2", "l2-simple-5-3",
  "l2-simple-5-4", "l2-simple-6-0", "l2-simple-6-1", "l2-simple-6-2", "l2-simple-6-3", "l2-simple-7-0",
  "l2-simple-7-1", "l2-simple-7-2", "l2-simple-8-0", "l2-simple-8-1", "l2-simple-9-0", "l2-simple-10-0",
  "l2-simple-11-1", "l2-simple-11-2", "l2-simple-11-3", "l2-simple-11-4", "l2-simple-11-5", "l2-simple-11-6",
  "l2-simple-11-7", "l2-simple-11-8", "l2-simple-11-9", "l2-simple-12-1", "l2-simple-12-2", "l2-simple-12-3",
  "l2-simple-12-4", "l2-simple-12-5", "l2-simple-12-6", "l2-simple-12-7", "l2-simple-12-8", "l2-simple-12-9",
  "l2-simple-13-1", "l2-simple-13-2", "l2-simple-13-3", "l2-simple-13-4", "l2-simple-13-5", "l2-simple-13-6",
  "l2-simple-13-7", "l2-simple-13-8", "l2-simple-13-9", "l2-simple-14-1", "l2-simple-14-2", "l2-simple-14-3",
  "l2-simple-14-4", "l2-simple-14-5", "l2-simple-14-6", "l2-simple-14-7", "l2-simple-14-8", "l2-simple-14-9",
  "l2-simple-15-1", "l2-simple-15-2", "l2-simple-15-3", "l2-simple-15-4", "l2-simple-15-5", "l2-simple-15-6",
  "l2-simple-15-7", "l2-simple-15-8", "l2-simple-15-9", "l2-simple-16-1", "l2-simple-16-2", "l2-simple-16-3",
  "l2-simple-16-4", "l2-simple-16-5", "l2-simple-16-6", "l2-simple-16-7", "l2-simple-16-8", "l2-simple-16-9",
  "l2-simple-17-1", "l2-simple-17-2", "l2-simple-17-3", "l2-simple-17-4", "l2-simple-17-5", "l2-simple-17-6",
  "l2-simple-17-7", "l2-simple-17-8", "l2-simple-17-9", "l2-simple-18-1", "l2-simple-18-2", "l2-simple-18-3",
  "l2-simple-18-4", "l2-simple-18-5", "l2-simple-18-6", "l2-simple-18-7", "l2-simple-18-8", "l2-simple-18-9",
  "l2-simple-19-1", "l2-simple-19-2", "l2-simple-19-3", "l2-simple-19-4", "l2-simple-19-5", "l2-simple-19-6",
  "l2-simple-19-7", "l2-simple-19-8", "l2-simple-19-9", "l2-simple-20-1", "l2-simple-20-2", "l2-simple-20-3",
  "l2-simple-20-4", "l2-simple-20-5", "l2-simple-20-6", "l2-simple-20-7", "l2-simple-20-8", "l2-simple-20-9",
  "l3-rwd-11-1-12", "l3-rwd-11-2-13", "l3-rwd-11-3-14", "l3-rwd-11-4-15", "l3-rwd-11-5-16", "l3-rwd-11-6-17",
  "l3-rwd-11-7-18", "l3-rwd-11-8-19", "l3-rwd-11-9-20", "l3-rwd-12-1-13", "l3-rwd-12-2-14", "l3-rwd-12-3-15",
  "l3-rwd-12-4-16", "l3-rwd-12-5-17", "l3-rwd-12-6-18", "l3-rwd-12-7-19", "l3-rwd-12-8-20", "l3-rwd-13-1-14",
  "l3-rwd-13-2-15", "l3-rwd-13-3-16", "l3-rwd-13-4-17", "l3-rwd-13-5-18", "l3-rwd-13-6-19", "l3-rwd-13-7-20",
  "l3-rwd-14-1-15", "l3-rwd-14-2-16", "l3-rwd-14-3-17", "l3-rwd-14-4-18", "l3-rwd-14-5-19", "l3-rwd-14-6-20",
  "l3-rwd-15-1-16", "l3-rwd-15-2-17", "l3-rwd-15-3-18", "l3-rwd-15-4-19", "l3-rwd-15-5-20", "l3-rwd-16-1-17",
  "l3-rwd-16-2-18", "l3-rwd-16-3-19", "l3-rwd-16-4-20", "l3-rwd-17-1-18", "l3-rwd-17-2-19", "l3-rwd-17-3-20",
  "l3-rwd-18-1-19", "l3-rwd-18-2-20", "l3-rwd-19-1-20", "l3-rwd-20-1-21", "l3-rwd-20-2-22", "l3-rwd-20-3-23",
  "l3-rwd-20-4-24", "l3-rwd-20-5-25", "l3-rwd-20-6-26", "l3-rwd-20-7-27", "l3-rwd-20-8-28", "l3-rwd-20-9-29",
  "l3-s1-11-1", "l3-s1-11-2", "l3-s1-11-3", "l3-s1-11-4", "l3-s1-11-5", "l3-s1-11-6",
  "l3-s1-11-7", "l3-s1-11-8", "l3-s1-11-9", "l3-s1-12-1", "l3-s1-12-2", "l3-s1-12-3",
  "l3-s1-12-4", "l3-s1-12-5", "l3-s1-12-6", "l3-s1-12-7", "l3-s1-12-8", "l3-s1-13-1",
  "l3-s1-13-2", "l3-s1-13-3", "l3-s1-13-4", "l3-s1-13-5", "l3-s1-13-6", "l3-s1-13-7",
  "l3-s1-14-1", "l3-s1-14-2", "l3-s1-14-3", "l3-s1-14-4", "l3-s1-14-5", "l3-s1-14-6",
  "l3-s1-15-1", "l3-s1-15-2", "l3-s1-15-3", "l3-s1-15-4", "l3-s1-15-5", "l3-s1-16-1",
  "l3-s1-16-2", "l3-s1-16-3", "l3-s1-16-4", "l3-s1-17-1", "l3-s1-17-2", "l3-s1-17-3",
  "l3-s1-18-1", "l3-s1-18-2", "l3-s1-19-1", "l3-s1-20-1", "l3-s1-20-2", "l3-s1-20-3",
  "l3-s1-20-4", "l3-s1-20-5", "l3-s1-20-6", "l3-s1-20-7", "l3-s1-20-8", "l3-s1-20-9",
  "l3-s2-0-1", "l3-s2-0-2", "l3-s2-0-3", "l3-s2-0-4", "l3-s2-0-5", "l3-s2-0-6",
  "l3-s2-0-7", "l3-s2-0-8", "l3-s2-0-9", "l3-s2-1-1", "l3-s2-1-2", "l3-s2-1-3",
  "l3-s2-1-4", "l3-s2-1-5", "l3-s2-1-6", "l3-s2-1-7", "l3-s2-1-8", "l3-s2-1-9",
  "l3-s2-2-1", "l3-s2-2-2", "l3-s2-2-3", "l3-s2-2-4", "l3-s2-2-5", "l3-s2-2-6",
  "l3-s2-2-7", "l3-s2-2-8", "l3-s2-3-1", "l3-s2-3-2", "l3-s2-3-3", "l3-s2-3-4",
  "l3-s2-3-5", "l3-s2-3-6", "l3-s2-3-7", "l3-s2-4-1", "l3-s2-4-2", "l3-s2-4-3",
  "l3-s2-4-4", "l3-s2-4-5", "l3-s2-4-6", "l3-s2-5-1", "l3-s2-5-2", "l3-s2-5-3",
  "l3-s2-5-4", "l3-s2-5-5", "l3-s2-6-1", "l3-s2-6-2", "l3-s2-6-3", "l3-s2-6-4",
  "l3-s2-7-1", "l3-s2-7-2", "l3-s2-7-3", "l3-s2-8-1", "l3-s2-8-2", "l3-s2-9-1",
  "l3-s3-1", "l3-s3-2", "l3-s3-3", "l3-s3-4", "l3-s3-5", "l3-s3-6",
  "l3-s3-7", "l3-s3-8", "l3-s3-9", "l3-s3-10",
  "l5-rwd-11-11-22", "l5-rwd-11-12-23", "l5-rwd-11-13-24", "l5-rwd-11-14-25", "l5-rwd-11-15-26", "l5-rwd-11-16-27",
  "l5-rwd-11-17-28", "l5-rwd-11-18-29", "l5-rwd-12-11-23", "l5-rwd-12-12-24", "l5-rwd-12-13-25", "l5-rwd-12-14-26",
  "l5-rwd-12-15-27", "l5-rwd-12-16-28", "l5-rwd-12-17-29", "l5-rwd-13-11-24", "l5-rwd-13-12-25", "l5-rwd-13-13-26",
  "l5-rwd-13-14-27", "l5-rwd-13-15-28", "l5-rwd-13-16-29", "l5-rwd-14-11-25", "l5-rwd-14-12-26", "l5-rwd-14-13-27",
  "l5-rwd-14-14-28", "l5-rwd-14-15-29", "l5-rwd-15-11-26", "l5-rwd-15-12-27", "l5-rwd-15-13-28", "l5-rwd-15-14-29",
  "l5-rwd-16-11-27", "l5-rwd-16-12-28", "l5-rwd-16-13-29", "l5-rwd-17-11-28", "l5-rwd-17-12-29", "l5-rwd-18-11-29",
  "l5-s1-11-11", "l5-s1-11-12", "l5-s1-11-13", "l5-s1-11-14", "l5-s1-11-15", "l5-s1-11-16",
  "l5-s1-11-17", "l5-s1-11-18", "l5-s1-12-11", "l5-s1-12-12", "l5-s1-12-13", "l5-s1-12-14",
  "l5-s1-12-15", "l5-s1-12-16", "l5-s1-12-17", "l5-s1-13-11", "l5-s1-13-12", "l5-s1-13-13",
  "l5-s1-13-14", "l5-s1-13-15", "l5-s1-13-16", "l5-s1-14-11", "l5-s1-14-12", "l5-s1-14-13",
  "l5-s1-14-14", "l5-s1-14-15", "l5-s1-15-11", "l5-s1-15-12", "l5-s1-15-13", "l5-s1-15-14",
  "l5-s1-16-11", "l5-s1-16-12", "l5-s1-16-13", "l5-s1-17-11", "l5-s1-17-12", "l5-s1-18-11",
  "l5-s2-11-11", "l5-s2-11-12", "l5-s2-11-13", "l5-s2-11-14", "l5-s2-11-15", "l5-s2-11-16",
  "l5-s2-11-17", "l5-s2-11-18", "l5-s2-12-11", "l5-s2-12-12", "l5-s2-12-13", "l5-s2-12-14",
  "l5-s2-12-15", "l5-s2-12-16", "l5-s2-12-17", "l5-s2-13-11", "l5-s2-13-12", "l5-s2-13-13",
  "l5-s2-13-14", "l5-s2-13-15", "l5-s2-13-16", "l5-s2-14-11", "l5-s2-14-12", "l5-s2-14-13",
  "l5-s2-14-14", "l5-s2-14-15", "l5-s2-15-11", "l5-s2-15-12", "l5-s2-15-13", "l5-s2-15-14",
  "l5-s2-16-11", "l5-s2-16-12", "l5-s2-16-13", "l5-s2-17-11", "l5-s2-17-12", "l5-s2-18-11",
  "l5-s3-1-1", "l5-s3-1-2", "l5-s3-1-3", "l5-s3-1-4", "l5-s3-1-5", "l5-s3-1-6",
  "l5-s3-1-7", "l5-s3-1-8", "l5-s3-2-1", "l5-s3-2-2", "l5-s3-2-3", "l5-s3-2-4",
  "l5-s3-2-5", "l5-s3-2-6", "l5-s3-2-7", "l5-s3-3-1", "l5-s3-3-2", "l5-s3-3-3",
  "l5-s3-3-4", "l5-s3-3-5", "l5-s3-3-6", "l5-s3-4-1", "l5-s3-4-2", "l5-s3-4-3",
  "l5-s3-4-4", "l5-s3-4-5", "l5-s3-5-1", "l5-s3-5-2", "l5-s3-5-3", "l5-s3-5-4",
  "l5-s3-6-1", "l5-s3-6-2", "l5-s3-6-3", "l5-s3-7-1", "l5-s3-7-2", "l5-s3-8-1",
  "l5-s4", "l5-s5-2", "l5-s5-3", "l5-s5-4", "l5-s5-5", "l5-s5-6",
  "l5-s5-7", "l5-s5-8", "l5-s5-9",
"lvl-1-decomp-eq", "lvl-1-decomp-pre",
  "lvl-1-greeting", "lvl-1-intro", "lvl-2-step-1-eq", "lvl-2-step-1-or", "lvl-2-step-1-pre", "lvl-2-step-1-q",
  "lvl-2-step-2-big-pre", "lvl-2-step-2-find", "lvl-2-step-2-friend-pre", "lvl-2-step-2-q", "lvl-2-step-3-can-split", "lvl-2-step-3-q",
  "lvl-2-step-3-split-pre", "lvl-2-step-4-calc", "lvl-2-step-4-split", "lvl-3-intro", "lvl-3-step-1-pre", "lvl-3-step-1-q",
  "lvl-3-step-1-split", "lvl-3-step-2-pre", "lvl-done", "n-0", "n-1", "n-2",
  "n-3", "n-4", "n-5", "n-6", "n-7", "n-8",
  "n-9", "n-10", "n-11", "n-12", "n-13", "n-14",
  "n-15", "n-16", "n-17", "n-18", "n-19", "panda-cheer-1",
  "panda-cheer-2", "panda-praise-1", "panda-praise-2", "panda-praise-3", "q-equals", "q-plus",
  "q-what-is", "whack-correct", "whack-done", "whack-down", "whack-intro", "whack-near",
  "whack-next", "whack-pop", "whack-q-pre", "whack-start", "whack-tap", "whack-timeup"
];

// Lazy audio pool. With ~2000 pool-driven composite cues, eager
// construction would hit Chrome's per-page WebMediaPlayer cap
// (crbug.com/1144736 — typically ~50 <audio> elements per tab) and
// burn ~20 MB of upfront memory for cues that may never fire in a
// given session. Instead we build each Audio element on first access
// via a Proxy, then cache it. Safari/iPad doesn't have the Chrome
// cap, but the lazy pattern is harmless there and keeps `audioUnlocked`
// semantics tight (only the cues the kid actually heard get the unlock
// play/pause cycle, instead of every mp3 in the manifest).
const audioCache = new Map();
// Audio elements that were materialized (via the Proxy below) AFTER the
// last user gesture. iPad Safari only allows `.play()` to actually start
// playback for elements whose first play/pause cycle ran inside a user
// activation — otherwise the call rejects with "the user didn't interact
// with the document first" (user-visible as silent failure on every pool-
// driven composite cue the first time it's requested, e.g. l3-s1-12-6).
// We can't unlock these lazily at creation time (the Proxy often runs
// outside a gesture — inside scene init, inside a `playSequence` chain),
// so we mark them and drain the set on the next pointerdown. drainNeedsUnlock()
// is called from the gesture handler at the bottom of this file.
const needsUnlock = new WeakSet();
// Set of valid cue ids for O(1) lookup in the Proxy traps below — built
// once from CUE_IDS at boot. Probing `CUE_IDS.includes(id)` per access
// would be O(n) and slow the audio pool down on every playCue().
const validCueIds = new Set(CUE_IDS);
const audio = new Proxy({}, {
  get(_, id) {
    if (typeof id !== "string") return undefined;
    // Reject ids not in CUE_IDS — both deleted cues (panda-celebrate /
    // enc-try / enc-great etc., removed when the tier system landed)
    // and typo'd cue strings. Returning a real <audio> element for
    // these would either silently replay the deleted cue (if the mp3
    // still exists on disk from a build prior to deletion) or create
    // a phantom element with no playback source. The
    // `audio/panda-audio not loaded` warn in playCue catches the
    // typo case instead.
    if (!validCueIds.has(id)) return undefined;
    let el = audioCache.get(id);
    if (!el) {
      // MP3 from Tencent TTS (see tools/build-audio-tencent.mjs) and
      // tools/build-composite-audio.mjs. Safari on iPad and Chromium
      // on desktop both handle MP3 in <audio> natively.
      el = new Audio(`assets/audio/${id}.mp3`);
      el.preload = "auto";
      el.dataset.cue = id;
      audioCache.set(id, el);
      // Mark for unlock on the next user gesture — see the WeakSet
      // comment above. This is the only line that's different from
      // a vanilla lazy-Audio pool: every newly-materialized element
      // gets one play/pause cycle inside a gesture before its first
      // real play() attempt.
      needsUnlock.add(el);
    }
    return el;
  },
  has(_, id) {
    return typeof id === "string" && validCueIds.has(id);
  },
  ownKeys() { return [...CUE_IDS]; },
  getOwnPropertyDescriptor(_, id) {
    if (typeof id !== "string" || !validCueIds.has(id)) return undefined;
    // Touch the proxy getter so the cache is populated, then expose
    // it as an enumerable own property so `Object.keys(audio)` /
    // `Object.values(audio)` (used by unlockAudio below) see every
    // declared cue — but only iterate when actually called, so the
    // Proxy `get` still does the lazy creation.
    const el = audio[id];
    return {
      value: el,
      writable: false,
      enumerable: true,
      configurable: true,
    };
  },
});

let audioUnlocked = false;
function unlockAudio() {
  if (audioUnlocked) return;
  // Iterate only the cues that have already been materialized via the
  // Proxy — `audio` is lazy, so an unbounded Object.values() here would
  // force-create every Audio element in CUE_IDS and re-introduce the
  // Chrome WebMediaPlayer cap (crbug.com/1144736). The cues the kid
  // hasn't heard yet stay un-cached and unlock the first time they fire.
  for (const el of audioCache.values()) {
    const wasMuted = el.muted;
    el.muted = true;
    const p = el.play();
    const restore = () => {
      el.pause();
      // iPad Safari throws InvalidStateError on currentTime = 0 when the
      // element hasn't fully decoded yet (same race as playCueRaw).
      try { el.currentTime = 0; } catch (_) { /* Safari pre-metadata */ }
      el.muted = wasMuted;
    };
    if (p && typeof p.then === "function") {
      p.then(restore).catch(() => { el.muted = wasMuted; });
    } else {
      restore();
    }
  }
  audioUnlocked = true;
}

// Drains every audio element that the Proxy marked as needs-unlock. Runs
// inside the pointerdown handler so `.play()` happens inside a user
// gesture — that's the only context in which iPad Safari will accept
// future play() calls on those elements. Silent (muted), then paused
// immediately, then back to its previous muted state. Called on every
// pointerdown so cues materializing in the middle of a session (the
// common case for pool-driven composites like l3-s1-12-6) still get
// unlocked before the next kid-driven cue fires.
function drainNeedsUnlock() {
  for (const el of audioCache.values()) {
    if (!needsUnlock.has(el)) continue;
    // Skip elements that are currently playing — they're already
    // unlocked by the act of playing, AND a play→pause→currentTime=0
    // cycle would interrupt any in-flight playback (e.g. a playAfter
    // chain mid-cue). Without this guard, the pointerdown that follows
    // a round-5 correct balloon tap resets lvl-done mid-playback and
    // its `ended` event never fires — the chain hangs and the scene
    // never advances to gamesPicker. Hit on a real iPad in 2026-08-13.
    if (!el.paused) continue;
    const wasMuted = el.muted;
    el.muted = true;
    const p = el.play();
    const restore = () => {
      el.pause();
      try { el.currentTime = 0; } catch (_) { /* Safari pre-metadata */ }
      el.muted = wasMuted;
      needsUnlock.delete(el);
    };
    if (p && typeof p.then === "function") {
      p.then(restore).catch(() => { el.muted = wasMuted; needsUnlock.delete(el); });
    } else {
      restore();
    }
  }
}

// Pool-driven composite cue ids per level. Mirrors the per-round id
// emission in tools/_emit-cues.mjs exactly — if that script adds a new
// pattern, this function must be updated to match (or the unlock will
// silently miss cues the kid will hear).
//
// Kept inline rather than imported from the build script so the browser
// side has zero dependency on the Node toolchain.
function isMakeTenRound(nums) {
  for (let i = 0; i < nums.length; i++) {
    for (let j = i + 1; j < nums.length; j++) {
      if (nums[i] + nums[j] === 10) return true;
    }
  }
  return false;
}

function choosePairForCueIds(nums) {
  // Mirror of scenes/level1.js's choosePair — always pair the first two
  // addends, since L1's pool is sum-≤-10 only (no make-a-ten shortcut).
  // scenes/level2.js uses the same shape for its (a, b, c) triples.
  if (nums[0] + nums[1] === 10) return { pair: [nums[0], nums[1]], third: nums[2] };
  if (nums[1] + nums[2] === 10) return { pair: [nums[1], nums[2]], third: nums[0] };
  return { pair: [nums[0], nums[1]], third: nums[2] };
}

function computePoolCueIds(levelId) {
  const ids = new Set();
  if (levelId === 1) {
    for (const r of poolGens[1]()) {
      const [a, b, c] = r.nums;
      const { pair, third } = choosePairForCueIds(r.nums);
      if (isMakeTenRound(r.nums)) {
        ids.add(`l1-intro-mt-${a}-${b}-${c}`);
        ids.add(`l1-sub-find-ten`);
      } else {
        ids.add(`l1-intro-${a}-${b}-${c}`);
        ids.add(`l1-sub-${pair[0]}-${pair[1]}`);
      }
      ids.add(`l1-step2-${pair[0] + pair[1]}-${third}`);
      ids.add(`l1-rwd-${a}-${b}-${c}-${r.answer}`);
    }
  } else if (levelId === 2) {
    for (const r of poolGens[2]()) {
      const [a, b] = r.nums;
      ids.add(`l2-simple-${a}-${b}`);
      ids.add(`l2-rwd-${a}-${b}-${r.answer}`);
    }
  } else if (levelId === 3 || levelId === 4) {
    // L4 reuses the L3 cue naming (see scenes/level4.js header comment),
    // and the L4 pool is a strict subset of the L3 pool structure, so
    // iterating the L3 pool pre-unlocks everything L4 will ever play.
    for (const r of poolGens[3]()) {
      const ones = r.a % 10;
      const sum = ones + r.b;
      ids.add(`l3-s1-${r.a}-${r.b}`);
      ids.add(`l3-s2-${ones}-${r.b}`);
      ids.add(`l3-s3-${sum}`);
      ids.add(`l3-rwd-${r.a}-${r.b}-${r.answer}`);
    }
  } else if (levelId === 5) {
    // L5 十几加十几 — 5 步预生成 MP3 + 奖励。
    // cue 模板：
    //   l5-s1-{a}-{b}    拆 a
    //   l5-s2-{a}-{b}    拆 b
    //   l5-s3-{oA}-{oB}  加个位
    //   l5-s4            静态"十加十等于 20"
    //   l5-s5-{sum}      加起来
    //   l5-rwd-{a}-{b}-{answer}   完整算式读出
    for (const r of poolGens[5]()) {
      ids.add(`l5-s1-${r.a}-${r.b}`);
      ids.add(`l5-s2-${r.a}-${r.b}`);
      ids.add(`l5-s3-${r.onesA}-${r.onesB}`);
      ids.add(`l5-s4`);
      ids.add(`l5-s5-${r.sum}`);
      ids.add(`l5-rwd-${r.a}-${r.b}-${r.answer}`);
    }
  }
  return ids;
}

// Pre-unlock every pool-driven composite cue for a level. MUST be called
// from inside a user gesture (level picker onClick / card.onPick) — iPad
// Safari only accepts .play() for elements whose first play/pause cycle
// ran inside a user activation, and the level card tap is the only
// gesture available before roundScene's first .play() attempt.
//
// Without this, the first play() of l3-s1-12-6 (or whichever pool cue
// round 0 fires) rejects with "user didn't interact with the document
// first" and the kid hears silence for the entire first round. The
// fix the user reported 2026-08-12 ("用户第一次进来点击时，必然出现").
//
// Static cues (enc-*, panda-praise-*, panda-cheer-*, enc-wrong-*,
// enc-near-*, enc-specific-*) are NOT pre-unlocked here — they fire
// in roundScene only after the kid has tapped an answer, which is a
// gesture, and drainNeedsUnlock in the pointerdown handler picks them
// up. Including them would balloon the cue set and hit Chrome's
// WebMediaPlayer cap (crbug.com/1144736).
function unlockLevelPool(levelId) {
  const ids = computePoolCueIds(levelId);
  for (const id of ids) {
    const el = audio[id];
    if (!el) continue;          // unknown id, leave to playCue's no-element warn
    if (!needsUnlock.has(el)) continue;  // already unlocked by an earlier gesture
    el.muted = true;
    const p = el.play();
    const restore = () => {
      el.pause();
      try { el.currentTime = 0; } catch (_) { /* Safari pre-metadata */ }
      el.muted = false;
      needsUnlock.delete(el);
    };
    if (p && typeof p.then === "function") {
      p.then(restore).catch(() => { el.muted = false; needsUnlock.delete(el); });
    } else {
      restore();
    }
  }
}

// Plays a single cue's audio element from the start. Use playCueRaw()
// from inside a chain (playSequence / playAfter / scheduleCue) — it
// plays without the global mutex, so chained cues don't cancel each
// other mid-flight. Use playCue() from any external caller: it first
// calls stopAllAudio() so a direct trigger can never overlap with an
// in-flight chain (this is the safety net for "user pressed button
// while previous audio was still going" — the design rule is "at most
// one active audio at any moment").
function playCueRaw(id) {
  const el = audio[id];
  if (!el) {
    console.warn(`[panda-audio] playCue("${id}"): no audio element`);
    return;
  }
  try {
    el.muted = false;
    el.volume = 1;
    // iPad Safari throws InvalidStateError on el.currentTime = 0 when
    // the element hasn't fully decoded metadata yet (e.g. right after
    // a cold load). Wrap so a stuck reset doesn't abort the whole
    // play() — the play() below still works, just starting from where
    // the element already is.
    try { el.currentTime = 0; } catch (_) { /* Safari pre-metadata */ }
    const p = el.play();
    if (p && typeof p.catch === "function") {
      p.catch((err) => {
        // iPad Safari often rejects the very first play() of a freshly
        // loaded MP3 with NotAllowedError even after the unlock pattern —
        // log it so the user can tell us which cues are silently failing.
        console.warn(`[panda-audio] playCue("${id}") rejected:`, err?.message || err);
      });
    }
  } catch (err) {
    console.warn(`[panda-audio] playCue("${id}") threw:`, err?.message || err);
  }
}

function playCue(id) {
  // Mutex: any direct cue trigger cancels any in-flight chain first.
  // This guarantees the "at most one active audio" invariant for every
  // external caller without each call site having to remember. Chains
  // use playCueRaw() to bypass this so they don't cancel themselves.
  stopAllAudio();
  playCueRaw(id);
}

// Every scheduled cue (from playSequence, playAfter, or anywhere that uses
// scheduleCue) is tracked here so a correct pick can cancel all of them
// at once. Without this, a child who answers mid-sentence would hear the
// remaining words of the L1 decompose overlap with the encouragement +
// the next step's audio prompt — a wall of sound.
const pendingCueTimers = new Set();
function scheduleCue(id, delayMs) {
  const tid = setTimeout(() => {
    pendingCueTimers.delete(tid);
    playCue(id);
  }, delayMs);
  pendingCueTimers.add(tid);
  return tid;
}

// Every active playAfter() registers a context here so stopAllAudio can
// (a) cancel the fallback setTimeout that fires when iPad Safari misses
// the reference cue's `ended` event, and (b) detach the reference cue's
// `ended` listener so a re-entered scene's fresh play() of the same
// audio element doesn't accidentally fire a stale kickoff. Without
// this, tapping the back button while a step's audio was scheduled off
// the cheer chain would let the fallback fire ~2s later and start the
// next chain in the destination scene (the user reported "audio is
// still playing after I tap ←").
const activeAfters = new Set();
const afterFallbackTimers = new Set();

// Cancels all queued cues, marks every active sequence as cancelled so
// future `ended` events in the chain are no-ops, detaches every pending
// playAfter's `ended` listener and cancels its fallback timer, and
// pauses every currently-playing audio element. Used when a child taps
// an answer (right or wrong) or navigates away — the rest of any
// spoken sentence should never fight with the next audio.
function stopAllAudio() {
  pendingCueTimers.forEach((tid) => clearTimeout(tid));
  pendingCueTimers.clear();
  for (const seq of activeSequences) seq.cancelled = true;
  activeSequences.clear();
  afterFallbackTimers.forEach((tid) => clearTimeout(tid));
  afterFallbackTimers.clear();
  for (const ctx of activeAfters) {
    ctx.cancelled = true;
    if (ctx.onEnded && ctx.ref) {
      try { ctx.ref.removeEventListener("ended", ctx.onEnded); } catch (_) {}
    }
  }
  activeAfters.clear();
  // Iterate only the cues that have actually been materialized — same
  // reason as unlockAudio above. A cue that hasn't fired yet has no
  // <audio> element to pause, and forcing one to exist would defeat
  // the lazy pool and re-introduce Chrome's WebMediaPlayer cap.
  for (const el of audioCache.values()) {
    if (!el.paused) {
      try { el.pause(); } catch (_) {}
    }
  }
}

// Plays a series of cue ids chained strictly by each cue's `ended`
// event — not by a setTimeout estimate of audio.duration. A slow system
// that decodes audio slowly won't make the next cue fire too early, and
// the chain breaks cleanly when stopAllAudio pauses the audio (the
// `ended` event never fires, no further cues land).
//
// seqGapMs (default 90) is the silence between consecutive cues. It's a
// fixed padding for breathing room, not a timing estimate — the next
// cue is guaranteed to wait for the previous one to fully finish.
//
// startDelayMs (optional) is the silence before the first cue. Prefer
// playAfter() when you need to wait for another cue to end; that uses
// the audio's `ended` event for the wait, then hands the gapMs to
// playSequence as startDelayMs.
//
// onComplete (optional) fires once the entire chain has played through
// — specifically, after the LAST cue's `ended` event. Callers that need
// to gate UI on the audio finishing (e.g. roundScene waiting to
// transition to the next round) pass a callback here instead of
// estimating audio durations. The callback does NOT fire if the chain
// is cancelled by stopAllAudio — the caller is responsible for a
// fallback timeout if the user might navigate mid-sequence.
//
// In test mode (window.__skipTimers), the chain is bypassed and
// onComplete fires immediately, so verifiers don't hang waiting on
// audio events that never fire in headless browsers.
//
// Each sequence is tracked in activeSequences so stopAllAudio can
// cancel the whole chain (e.g. a kid who taps an answer mid-sentence
// should hear silence, not the remaining 12 words).
const activeSequences = new Set();

function playSequence(ids, seqGapMs = 90, startDelayMs = 0, onComplete) {
  if (!Array.isArray(ids) || ids.length === 0) {
    if (onComplete) onComplete();
    return;
  }
  // Verifier mode: skip playback and resolve immediately so audio-gated
  // advances don't hang waiting on events that never fire.
  if (window.__skipTimers) {
    if (onComplete) onComplete();
    return;
  }
  const seq = { cancelled: false };
  activeSequences.add(seq);

  const playIdx = (i) => {
    if (seq.cancelled || i >= ids.length) {
      if (i >= ids.length) {
        activeSequences.delete(seq);
        // If the chain finished naturally (not via stopAllAudio
        // cancellation), signal completion so the caller can advance.
        if (!seq.cancelled && onComplete) onComplete();
      }
      return;
    }
    const el = audio[ids[i]];
    if (!el) {
      // Silent no-op when a cue isn't preloaded — but log it so a missing
      // audio file (e.g. a newly-added composite cue that hasn't been
      // built yet) is visible during dev instead of the kid hearing
      // nothing with no breadcrumb.
      console.warn(`[PandaAudio] cue "${ids[i]}" not loaded — chain continues silently. Re-run \`npm run audio:build\` if this is a new cue.`);
      activeSequences.delete(seq);
      if (onComplete) onComplete();
      return;
    }
    playCueRaw(ids[i]);
    if (i + 1 < ids.length) {
      // Closure-captured fired flag guards against iPad Safari
      // firing `ended` twice on the same element (it can if the
      // element was paused and re-played, or after a play() race).
      // Without this guard, the next cue in the chain would start
      // a second time and overlap with itself.
      let fired = false;
      el.addEventListener("ended", function onEnded() {
        el.removeEventListener("ended", onEnded);
        if (seq.cancelled || fired) return;
        fired = true;
        setTimeout(() => playIdx(i + 1), seqGapMs);
      });
    } else {
      // Last cue: fire onComplete AFTER its `ended` event so the
      // caller can chain a UI transition on the audio actually
      // finishing. (Without the wrapper, onComplete would fire when
      // the last cue STARTS, not when it ENDS.) Same fired guard as
      // above for Safari double-fire safety.
      let fired = false;
      el.addEventListener("ended", function onEnded() {
        el.removeEventListener("ended", onEnded);
        if (seq.cancelled || fired) return;
        fired = true;
        activeSequences.delete(seq);
        if (onComplete) onComplete();
      });
    }
  };

  if (startDelayMs > 0) {
    const tid = setTimeout(() => {
      pendingCueTimers.delete(tid);
      if (seq.cancelled) return;
      playIdx(0);
    }, startDelayMs);
    pendingCueTimers.add(tid);
  } else {
    playIdx(0);
  }
}

// Plays a sequence of cues after another cue's audio finishes, with a
// configurable gap. Uses the audio element's 'ended' event so the timing
// tracks reality (no race with audio.duration) — the L1 entry relies on
// this for the "greeting → 1s pause → decompose" transition, and L1
// step 2 uses it for the "encouragement → equation reward" handoff so
// the equation never starts mid-encouragement.
//
// If the reference cue has already ended (e.g. we re-entered a scene
// after the cue already played), the sequence fires immediately so the
// caller doesn't have to special-case the "already-played" branch.
//
// onComplete (optional) is forwarded to the underlying playSequence
// call — it fires when the FOLLOWING chain finishes, not when the
// reference cue ends. Use it to chain a UI action onto the audio
// fully landing (e.g. roundScene awaiting audio before advancing).
function playAfter(referenceId, ids, { gapMs = 1000, seqGapMs = 90 } = {}, onComplete) {
  // Test mode short-circuit — audio events never fire in headless
  // browsers, so don't block on `ref.ended` (it stays false forever).
  if (window.__skipTimers) {
    playSequence(ids, seqGapMs, 0, onComplete);
    return;
  }
  const ref = audio[referenceId];
  if (!ref) {
    // Reference cue doesn't exist — just play the sequence after a
    // generous fixed delay so the user still hears something.
    playSequence(ids, seqGapMs, 4000, onComplete);
    return;
  }
  // Per-playAfter context — registered with stopAllAudio so a
  // back-button tap (or any other navigation) can cancel the fallback
  // timer AND detach the `ended` listener. Without this, tapping ←
  // mid-cheer would let the fallback fire ~2s later in the destination
  // scene and start the step audio chain there ("audio still playing
  // after I tapped ←").
  const ctx = { cancelled: false, ref, onEnded: null };
  activeAfters.add(ctx);
  let fired = false;
  const kickoff = () => {
    if (fired || ctx.cancelled) return;
    fired = true;
    clearTimeout(fallback);
    afterFallbackTimers.delete(fallback);
    if (ctx.onEnded) {
      try { ctx.ref.removeEventListener("ended", ctx.onEnded); } catch (_) {}
    }
    activeAfters.delete(ctx);
    playSequence(ids, seqGapMs, gapMs, onComplete);
  };
  // Fallback timer: on iPad Safari the reference cue's `ended` event
  // sometimes never fires after the very first unlock — the play()
  // resolves but the metadata-driven `ended` event is missed, leaving
  // the kid in silence forever. Use the cue's known duration plus a
  // buffer as a wall-clock fallback. Whichever fires first wins.
  const durMs = (Number.isFinite(ref.duration) && ref.duration > 0)
    ? ref.duration * 1000
    : 6000; // generous default — L2/L3 spoken sentences can run 5-7s
  const fallback = setTimeout(kickoff, durMs + 2500);
  afterFallbackTimers.add(fallback);
  if (ref.ended) {
    kickoff();
    return;
  }
  ctx.onEnded = function onEnded() {
    ctx.ref.removeEventListener("ended", onEnded);
    kickoff();
  };
  ctx.ref.addEventListener("ended", ctx.onEnded);
}

const k = kaplay({
  width: 1366,
  height: 1024,
  letterbox: true,
  touchToMouse: true,
  canvas: document.getElementById("game"),
  background: [255, 241, 220],
  crisp: true,
  global: false,
});

window.kaplay = k;
window.PandaAudio = { audio, unlockAudio, unlockLevelPool, playCue, playSequence, playAfter, stopAllAudio, isUnlocked: () => audioUnlocked,
// Number of cues whose Audio element has been materialized so far. Tests
// use this instead of Object.keys(audio) — that would force-create every
// element in CUE_IDS and trip Chrome's WebMediaPlayer cap (~50 per tab).
audioMaterializedCount: () => audioCache.size,
};

// Wrap k.go so any scene transition (level card tap, back button, round
// transition, level-complete) stops the currently-speaking audio first.
// Without this, a kid who taps the L1 card while the L3 round is still
// reading its last cue would hear the rest of the L3 sentence on top of
// the L1 greeting — a wall of sound.
const _origGo = k.go.bind(k);
k.go = (name) => {
  window.PandaAudio.stopAllAudio();
  return _origGo(name);
};

// Art assets are illustrated PNGs under assets/art/, generated by
// tools/build-art-minimax.mjs and cut out to transparency. They replaced the
// earlier hand-authored SVGs, which were built from stroked primitives and read
// as thin line art on an iPad.
//
// These are fetched over HTTP, so the game must be served (see README) —
// double-clicking index.html will start but render without art. Each load is
// guarded individually: a missing or malformed file should cost the game its
// decoration, not its arithmetic. Components check k.getSprite() before drawing.
const SPRITES = [
  "panda-idle", "panda-cheer", "panda-think",
  "bamboo", "leaf",
  "star", "lock",
  "badge-1", "badge-2", "badge-3", "badge-4", "badge-5",
  // panda-park migrated game props
  "boat", "boat-sel", "cloud", "balloon", "bubble", "bubble-sel",
  // ten-frame: a hollow slot plus interchangeable counters, so the frame can
  // still fill one cell at a time
  "cell-frame",
  "dot-blue", "dot-yellow", "dot-pink", "dot-purple", "dot-orange",
  // equation glyphs (the digits themselves stay live text)
  "slot-answer", "op-plus", "op-equals",
  // full-bleed scene backdrops
  "bg-meadow", "bg-bamboo-grove",
  // whack-a-mole (added 2026-08-15): 6 ink moles + 3 hole variants + grass strip
  "mole-1", "mole-2", "mole-3", "mole-4", "mole-5", "mole-6",
  "mole-hole-1", "mole-hole-2", "mole-hole-3",
  "grass-ground",
  // baked mole+number PNGs (6 variants × 9 numbers = 54) — added 2026-08-15
  ...ALL_SPRITE_NAMES,
];

// Bumped whenever boat.png / boat-sel.png (or any other regenerated
// sprite) changes. Appended as a cache-buster query string so the browser
// doesn't keep serving the old raster after we replace the file on disk.
// Without this, the user can see a half-old / half-new sprite set
// (2026-08-12: top row of the boat grid was the cached old tan-sail
// boat.png while the bottom row got the new white-sail version, because
// the JS imports were cache-busted but the sprite URLs weren't).
const ART_VERSION = "20260815-mole";

function loadArt() {
  return Promise.all(
    SPRITES.map((name) =>
      Promise.resolve(k.loadSprite(name, `assets/art/${name}.png?v=${ART_VERSION}`)).catch((err) => {
        console.warn(`[panda] sprite "${name}" failed to load:`, err?.message || err);
        return null;
      }),
    ),
  );
}

function tryLockLandscape() {
  if (!screen.orientation || typeof screen.orientation.lock !== "function") return;
  screen.orientation.lock("landscape").catch((err) => {
    // Common on iPad Safari without user activation; will retry on first
    // pointerdown below. Don't spam the console — log only the first miss.
    console.debug("[panda] screen.orientation.lock rejected:", err?.message || err);
  });
}

// True when the viewport is taller than wide. screen.orientation.type is
// the most reliable signal where available; iPad Safari's matchMedia
// "(orientation: portrait)" can lag behind the actual rotation, so we
// also fall back to window dimensions.
function isPortrait() {
  const t = screen.orientation && screen.orientation.type;
  if (typeof t === "string") return t.startsWith("portrait");
  return window.innerHeight > window.innerWidth;
}

function watchOrientation() {
  const hint = document.getElementById("rotate-hint");
  if (!hint) return;
  const isCoarse = window.matchMedia("(pointer: coarse)").matches;
  const apply = () => {
    if (!isCoarse) { hint.hidden = true; return; }
    hint.hidden = !isPortrait();
  };
  apply();
  window.addEventListener("resize", apply);
  window.addEventListener("orientationchange", apply);
}

// Fire on page load so browsers that don't gate orientation.lock on
// user activation (Chrome on desktop, some Android browsers) snap to
// landscape immediately. iPad Safari will reject this — that's fine,
// the pointerdown handler below retries inside the user gesture.
tryLockLandscape();

// Tap-anywhere to unlock audio + attempt orientation lock. The lock
// succeeds inside this handler on iPad Safari because the pointerdown
// is a user activation. The hint overlay is also wired to call
// tryLockLandscape explicitly so tapping the hint's button works
// even if the canvas doesn't see the event.
document.addEventListener("pointerdown", () => {
  // Unlock lazily-materialized audio elements first — these are the
  // cues the kid has triggered since the last gesture (e.g. the step
  // audio that just played and rejected). unlockAudio() below runs
  // only on the FIRST gesture (audioUnlocked early-returns), so this
  // call is what keeps the unlock pattern working mid-session.
  drainNeedsUnlock();
  unlockAudio();
  tryLockLandscape();
}, { passive: true, once: false });

const rotateHint = document.getElementById("rotate-hint");
if (rotateHint) {
  rotateHint.addEventListener("click", () => {
    tryLockLandscape();
  });
}

watchOrientation();

(async () => {
  window.PandaLevels = levelsData;

  const [
    { default: levelPicker },
    { default: gamesPicker },
    { default: level1 },
    { default: level2 },
    { default: level3 },
    { default: level4 },
    { default: level5 },
    { default: dailyDone },
    { default: gameBoat },
    { default: gameBounce },
    { default: gameCloud },
    { default: gameFeed },
    { default: gameWhack },
  ] = await Promise.all([
    import("./scenes/levelPicker.js?v=20260815"),
    import("./scenes/gamesPicker.js?v=20260815"),
    import("./scenes/level1.js?v=20260815"),
    import("./scenes/level2.js?v=20260815"),
    import("./scenes/level3.js?v=20260815"),
    import("./scenes/level4.js?v=20260815"),
    import("./scenes/level5.js?v=20260815"),
    import("./scenes/dailyDone.js?v=20260815"),
    import("./scenes/gameBoat.js?v=20260815"),
    import("./scenes/gameBounce.js?v=20260815"),
    import("./scenes/gameCloud.js?v=20260815"),
    import("./scenes/gameFeed.js?v=20260815"),
    import("./scenes/gameWhack.js?v=20260815"),
  ]);

  // Sprites must be resolved before the first scene runs: scenes decide at build
  // time whether a sprite exists, so loading them afterwards would leave the
  // opening screen permanently art-less.
  await loadArt();

  k.scene("levelPicker", () => levelPicker(k));
  k.scene("gamesPicker", () => gamesPicker(k));
  k.scene("level1", () => level1(k));
  k.scene("level2", () => level2(k));
  k.scene("level3", () => level3(k));
  k.scene("level4", () => level4(k));
  k.scene("level5", () => level5(k));
  k.scene("dailyDone", () => dailyDone(k));
  k.scene("gameBoat",   () => gameBoat(k));
  k.scene("gameBounce", () => gameBounce(k));
  k.scene("gameCloud",  () => gameCloud(k));
  k.scene("gameFeed",   () => gameFeed(k));
  k.scene("gameWhack",  () => gameWhack(k));

  k.go("levelPicker");
})();