// main.js — Panda H5 (Kaplay) boot + audio pool + iPad viewport plumbing.
// No build step. Loads scenes and components from ./scenes and ./components.
//
// levels data is inlined as a JS const (not fetched, not JSON-imported) so
// the game boots under the file:// protocol on iPad Safari, where fetch()
// is blocked and JSON module imports require the assert { type: "json" }
// attribute that older WebKit builds do not honor. data/levels.json stays
// in the repo as a single source of truth for offline editing.

import kaplay from "./assets/vendor/kaplay.mjs";
import "./save.js";

const levelsData = {
  "levels": [
    {
      "id": 1,
      "title": "三数相加",
      "rounds": [
        { "kind": "three-sum", "nums": [2, 3, 4], "answer": 9 },
        { "kind": "three-sum", "nums": [1, 5, 3], "answer": 9 },
        { "kind": "three-ten",  "nums": [3, 7, 2], "answer": 12 },
        { "kind": "three-sum", "nums": [4, 2, 1], "answer": 7 },
        { "kind": "three-ten",  "nums": [6, 4, 5], "answer": 15 },
        { "kind": "three-sum", "nums": [2, 2, 3], "answer": 7 }
      ]
    },
    {
      "id": 2,
      "title": "凑十法",
      "intro": "lvl-2-intro",
      "rounds": [
        { "kind": "make-ten", "a": 8, "b": 5, "need": 2, "rest": 3, "answer": 13 },
        { "kind": "make-ten", "a": 7, "b": 6, "need": 3, "rest": 3, "answer": 13 },
        { "kind": "make-ten", "a": 9, "b": 4, "need": 1, "rest": 3, "answer": 13 },
        { "kind": "make-ten", "a": 7, "b": 6, "need": 3, "rest": 3, "answer": 13 },
        { "kind": "make-ten", "a": 8, "b": 6, "need": 2, "rest": 4, "answer": 14 },
        { "kind": "make-ten", "a": 9, "b": 7, "need": 1, "rest": 6, "answer": 16 }
      ]
    },
    {
      "id": 3,
      "title": "二十以内",
      "intro": "lvl-3-intro",
      "rounds": [
        // L3 (二十以内) redesigned: a is a 2-digit (tens digit = 1) and
        // b is a 1-digit, with ones(a) + b ≤ 10 (no carrying). Taught
        // in 3 steps — split a into 10 + ones, add ones + b, add 10 +
        // the sum. ones = a % 10, sum = ones + b. answer = 10 + sum.
        { "a": 11, "b": 8, "answer": 19 },
        { "a": 11, "b": 4, "answer": 15 },
        { "a": 12, "b": 5, "answer": 17 },
        { "a": 13, "b": 6, "answer": 19 },
        { "a": 14, "b": 4, "answer": 18 },
        { "a": 15, "b": 5, "answer": 20 }
      ]
    }
  ]
};

const CUE_IDS = [
  "enc-great", "enc-awesome", "enc-amazing", "enc-nice", "enc-try",
  "n-0", "n-1", "n-2", "n-3", "n-4", "n-5", "n-6", "n-7", "n-8", "n-9", "n-10",
  "n-11", "n-12", "n-13", "n-14", "n-15", "n-16", "n-17", "n-18", "n-19",
  // spoken equation intro — chained by PandaAudio.playSequence so the child
  // hears "几加三加五" instead of just "算一算". The Mandarin chain reads
  // naturally: "what is three plus five?" in three concatenated words.
  "q-what-is", "q-plus", "q-equals", "equals",
  // L1 entry — greeting plays once on entering the level, then the
  // per-round "decompose" sentence is built at runtime by chaining
  // these number-agnostic chunks with the universal n-* / q-* cues.
  // L1 step audio is the decompose sentence, not standalone one-word
  // cues — the old lvl1-step-1 ("找一对") and lvl1-step-2 ("加剩下的")
  // were removed. The step bar uses the renamed "两数相加" / "计算结果"
  // labels (see scenes/level1.js stepLabels).
  "lvl-1-greeting",
  "lvl-1-decomp-pre", "lvl-1-decomp-eq",
  "lvl-2-intro", "lvl-3-intro", "lvl-done",
  // L2 (凑十法) per-step contextual sentence chunks — see tools/cues.cjs.
  // The 4 teaching beats (compare / find friend / split / calculate) are
  // built at runtime in scenes/level2.js by chaining these number-agnostic
  // chunks with the universal n-* and q-* cues.
  "lvl-2-step-1-pre", "lvl-2-step-1-eq", "lvl-2-step-1-or", "lvl-2-step-1-q",
  "lvl-2-step-2-big-pre", "lvl-2-step-2-find", "lvl-2-step-2-friend-pre", "lvl-2-step-2-q",
  "lvl-2-step-3-split-pre", "lvl-2-step-3-can-split", "lvl-2-step-3-q",
  "lvl-2-step-4-split", "lvl-2-step-4-calc",
  // L3 (二十以内) per-step contextual sentence chunks. The 2 teaching
  // beats (split / add ones) are built at runtime in scenes/level3.js.
  // Step 1 uses three number-agnostic chunks; step 2 uses one. After
  // step 2 correct, a reward audio reads "a+b=answer" using universal
  // n-* / q-plus / equals cues.
  "lvl-3-step-1-pre", "lvl-3-step-1-split", "lvl-3-step-1-q",
  "lvl-3-step-2-pre",
  // The panda speaks on every correct pick — see components/panda.js.
  // The old `panda-hi` was unused and is dropped.
  "panda-celebrate",
  "boat-intro", "boat-pair", "boat-done",
  "cloud-intro", "cloud-pair", "cloud-done",
  "bounce-intro", "bounce-pop", "bounce-done",
  "whack-intro", "whack-start", "whack-tick", "whack-timeup", "whack-done",
  "feed-intro", "feed-nom", "feed-next", "feed-done",
  // ===== per-round composite cues =====
  // Each round's full sentence is one mp3 (e.g. "二加三加四等于九")
  // instead of a playSequence chain of single-syllable cues stitched
  // at runtime. Generated by tools/build-composite-audio.mjs from
  // data/levels.json. The number-agnostic chunks above (lvl-*-*-*,
  // n-*, q-*) are still used for the level intro / game intro cues
  // that don't have round-specific numbers.
  // L1 — 三数相加 (6 rounds)
  "l1-intro-2-3-4", "l1-intro-1-5-3", "l1-intro-3-7-2", "l1-intro-4-2-1", "l1-intro-6-4-5", "l1-intro-2-2-3",
  "l1-sub-2-3", "l1-sub-1-5", "l1-sub-3-7", "l1-sub-4-2", "l1-sub-6-4", "l1-sub-2-2",
  // L1 step 2 simplified question — "pairSum 加 third 等于几". Pre-baked
  // so the kid hears it as one phrase, not 4 chained cues (the old
  // [n-pairSum, q-plus, n-third, q-equals] read as 4 separate words).
  "l1-step2-5-4", "l1-step2-6-3", "l1-step2-10-2", "l1-step2-6-1", "l1-step2-10-5", "l1-step2-4-3",
  "l1-rwd-2-3-4-9", "l1-rwd-1-5-3-9", "l1-rwd-3-7-2-12", "l1-rwd-4-2-1-7", "l1-rwd-6-4-5-15", "l1-rwd-2-2-3-7",
  // L2 — 凑十法 (6 rounds; l2-s2-7 deduped since rounds 2 & 4 share big=7;
  //               l2-rwd-*-13 deduped since rounds 1-4 share answer=13)
  "l2-s1-8-5", "l2-s1-7-6", "l2-s1-9-4", "l2-s1-8-6", "l2-s1-9-7",
  "l2-s2-8", "l2-s2-7", "l2-s2-9",
  "l2-s3-5-2", "l2-s3-6-3", "l2-s3-4-1", "l2-s3-6-2", "l2-s3-7-1",
  "l2-s4-5-2-3-8", "l2-s4-6-3-3-7", "l2-s4-4-1-3-9", "l2-s4-6-2-4-8", "l2-s4-7-1-6-9",
  "l2-rwd-8-5-13", "l2-rwd-7-6-13", "l2-rwd-9-4-13", "l2-rwd-8-6-14", "l2-rwd-9-7-16",
  // L3 — 二十以内 (6 rounds; l3-rwd-*-19 deduped since rounds 1 & 3 share answer=19)
  "l3-s1-11-8", "l3-s1-11-4", "l3-s1-12-5", "l3-s1-13-6", "l3-s1-14-4", "l3-s1-15-5",
  "l3-s2-1-8", "l3-s2-1-4", "l3-s2-2-5", "l3-s2-3-6", "l3-s2-4-4", "l3-s2-5-5",
  "l3-s3-9", "l3-s3-5", "l3-s3-7", "l3-s3-8", "l3-s3-10",
  "l3-rwd-11-8-19", "l3-rwd-11-4-15", "l3-rwd-12-5-17", "l3-rwd-13-6-19", "l3-rwd-14-4-18", "l3-rwd-15-5-20",
];

const audio = {};
for (const id of CUE_IDS) {
  // MP3 from Edge TTS (see tools/build-audio-edge.mjs). Safari on iPad
  // and Chromium on desktop both handle MP3 in <audio> natively.
  const el = new Audio(`assets/audio/${id}.mp3`);
  el.preload = "auto";
  el.dataset.cue = id;
  audio[id] = el;
}

let audioUnlocked = false;
function unlockAudio() {
  if (audioUnlocked) return;
  for (const el of Object.values(audio)) {
    const wasMuted = el.muted;
    el.muted = true;
    const p = el.play();
    const restore = () => {
      el.pause();
      el.currentTime = 0;
      el.muted = wasMuted;
    };
    if (p && typeof p.then === "function") {
      p.then(restore).catch(() => { el.muted = wasMuted; });
    } else {
      restore();
    }
  }
  audioUnlocked = true;
}

// Plays a single cue's audio element from the start. Use playCueRaw()
// from inside a chain (playSequence / playAfter / scheduleCue) — it
// plays without the global mutex, so chained cues don't cancel each
// other mid-flight. Use playCue() from any external caller: it first
// calls stopAllAudio() so a direct trigger can never overlap with an
// in-flight chain (this is the safety net for "user pressed button
// while previous audio was still going" — the design rule is "at most
// one active audio at any moment").
function playCueRaw(id) {
  const el = audio[id];
  if (!el) {
    console.warn(`[panda-audio] playCue("${id}"): no audio element`);
    return;
  }
  try {
    el.muted = false;
    el.volume = 1;
    el.currentTime = 0;
    const p = el.play();
    if (p && typeof p.catch === "function") {
      p.catch((err) => {
        // iPad Safari often rejects the very first play() of a freshly
        // loaded MP3 with NotAllowedError even after the unlock pattern —
        // log it so the user can tell us which cues are silently failing.
        console.warn(`[panda-audio] playCue("${id}") rejected:`, err?.message || err);
      });
    }
  } catch (err) {
    console.warn(`[panda-audio] playCue("${id}") threw:`, err?.message || err);
  }
}

function playCue(id) {
  // Mutex: any direct cue trigger cancels any in-flight chain first.
  // This guarantees the "at most one active audio" invariant for every
  // external caller without each call site having to remember. Chains
  // use playCueRaw() to bypass this so they don't cancel themselves.
  stopAllAudio();
  playCueRaw(id);
}

// Every scheduled cue (from playSequence, playAfter, or anywhere that uses
// scheduleCue) is tracked here so a correct pick can cancel all of them
// at once. Without this, a child who answers mid-sentence would hear the
// remaining words of the L1 decompose overlap with the encouragement +
// the next step's audio prompt — a wall of sound.
const pendingCueTimers = new Set();
function scheduleCue(id, delayMs) {
  const tid = setTimeout(() => {
    pendingCueTimers.delete(tid);
    playCue(id);
  }, delayMs);
  pendingCueTimers.add(tid);
  return tid;
}

// Every active playAfter() registers a context here so stopAllAudio can
// (a) cancel the fallback setTimeout that fires when iPad Safari misses
// the reference cue's `ended` event, and (b) detach the reference cue's
// `ended` listener so a re-entered scene's fresh play() of the same
// audio element doesn't accidentally fire a stale kickoff. Without
// this, tapping the back button while a step's audio was scheduled off
// the cheer chain would let the fallback fire ~2s later and start the
// next chain in the destination scene (the user reported "audio is
// still playing after I tap ←").
const activeAfters = new Set();
const afterFallbackTimers = new Set();

// Cancels all queued cues, marks every active sequence as cancelled so
// future `ended` events in the chain are no-ops, detaches every pending
// playAfter's `ended` listener and cancels its fallback timer, and
// pauses every currently-playing audio element. Used when a child taps
// an answer (right or wrong) or navigates away — the rest of any
// spoken sentence should never fight with the next audio.
function stopAllAudio() {
  pendingCueTimers.forEach((tid) => clearTimeout(tid));
  pendingCueTimers.clear();
  for (const seq of activeSequences) seq.cancelled = true;
  activeSequences.clear();
  afterFallbackTimers.forEach((tid) => clearTimeout(tid));
  afterFallbackTimers.clear();
  for (const ctx of activeAfters) {
    ctx.cancelled = true;
    if (ctx.onEnded && ctx.ref) {
      try { ctx.ref.removeEventListener("ended", ctx.onEnded); } catch (_) {}
    }
  }
  activeAfters.clear();
  for (const el of Object.values(audio)) {
    if (!el.paused) {
      try { el.pause(); } catch (_) {}
    }
  }
}

// Plays a series of cue ids chained strictly by each cue's `ended`
// event — not by a setTimeout estimate of audio.duration. A slow system
// that decodes audio slowly won't make the next cue fire too early, and
// the chain breaks cleanly when stopAllAudio pauses the audio (the
// `ended` event never fires, no further cues land).
//
// seqGapMs (default 90) is the silence between consecutive cues. It's a
// fixed padding for breathing room, not a timing estimate — the next
// cue is guaranteed to wait for the previous one to fully finish.
//
// startDelayMs (optional) is the silence before the first cue. Prefer
// playAfter() when you need to wait for another cue to end; that uses
// the audio's `ended` event for the wait, then hands the gapMs to
// playSequence as startDelayMs.
//
// onComplete (optional) fires once the entire chain has played through
// — specifically, after the LAST cue's `ended` event. Callers that need
// to gate UI on the audio finishing (e.g. roundScene waiting to
// transition to the next round) pass a callback here instead of
// estimating audio durations. The callback does NOT fire if the chain
// is cancelled by stopAllAudio — the caller is responsible for a
// fallback timeout if the user might navigate mid-sequence.
//
// In test mode (window.__skipTimers), the chain is bypassed and
// onComplete fires immediately, so verifiers don't hang waiting on
// audio events that never fire in headless browsers.
//
// Each sequence is tracked in activeSequences so stopAllAudio can
// cancel the whole chain (e.g. a kid who taps an answer mid-sentence
// should hear silence, not the remaining 12 words).
const activeSequences = new Set();

function playSequence(ids, seqGapMs = 90, startDelayMs = 0, onComplete) {
  if (!Array.isArray(ids) || ids.length === 0) {
    if (onComplete) onComplete();
    return;
  }
  // Verifier mode: skip playback and resolve immediately so audio-gated
  // advances don't hang waiting on events that never fire.
  if (window.__skipTimers) {
    if (onComplete) onComplete();
    return;
  }
  const seq = { cancelled: false };
  activeSequences.add(seq);

  const playIdx = (i) => {
    if (seq.cancelled || i >= ids.length) {
      if (i >= ids.length) {
        activeSequences.delete(seq);
        // If the chain finished naturally (not via stopAllAudio
        // cancellation), signal completion so the caller can advance.
        if (!seq.cancelled && onComplete) onComplete();
      }
      return;
    }
    const el = audio[ids[i]];
    if (!el) {
      activeSequences.delete(seq);
      if (onComplete) onComplete();
      return;
    }
    playCueRaw(ids[i]);
    if (i + 1 < ids.length) {
      // Closure-captured fired flag guards against iPad Safari
      // firing `ended` twice on the same element (it can if the
      // element was paused and re-played, or after a play() race).
      // Without this guard, the next cue in the chain would start
      // a second time and overlap with itself.
      let fired = false;
      el.addEventListener("ended", function onEnded() {
        el.removeEventListener("ended", onEnded);
        if (seq.cancelled || fired) return;
        fired = true;
        setTimeout(() => playIdx(i + 1), seqGapMs);
      });
    } else {
      // Last cue: fire onComplete AFTER its `ended` event so the
      // caller can chain a UI transition on the audio actually
      // finishing. (Without the wrapper, onComplete would fire when
      // the last cue STARTS, not when it ENDS.) Same fired guard as
      // above for Safari double-fire safety.
      let fired = false;
      el.addEventListener("ended", function onEnded() {
        el.removeEventListener("ended", onEnded);
        if (seq.cancelled || fired) return;
        fired = true;
        activeSequences.delete(seq);
        if (onComplete) onComplete();
      });
    }
  };

  if (startDelayMs > 0) {
    const tid = setTimeout(() => {
      pendingCueTimers.delete(tid);
      if (seq.cancelled) return;
      playIdx(0);
    }, startDelayMs);
    pendingCueTimers.add(tid);
  } else {
    playIdx(0);
  }
}

// Plays a sequence of cues after another cue's audio finishes, with a
// configurable gap. Uses the audio element's 'ended' event so the timing
// tracks reality (no race with audio.duration) — the L1 entry relies on
// this for the "greeting → 1s pause → decompose" transition, and L1
// step 2 uses it for the "encouragement → equation reward" handoff so
// the equation never starts mid-encouragement.
//
// If the reference cue has already ended (e.g. we re-entered a scene
// after the cue already played), the sequence fires immediately so the
// caller doesn't have to special-case the "already-played" branch.
//
// onComplete (optional) is forwarded to the underlying playSequence
// call — it fires when the FOLLOWING chain finishes, not when the
// reference cue ends. Use it to chain a UI action onto the audio
// fully landing (e.g. roundScene awaiting audio before advancing).
function playAfter(referenceId, ids, { gapMs = 1000, seqGapMs = 90 } = {}, onComplete) {
  // Test mode short-circuit — audio events never fire in headless
  // browsers, so don't block on `ref.ended` (it stays false forever).
  if (window.__skipTimers) {
    playSequence(ids, seqGapMs, 0, onComplete);
    return;
  }
  const ref = audio[referenceId];
  if (!ref) {
    // Reference cue doesn't exist — just play the sequence after a
    // generous fixed delay so the user still hears something.
    playSequence(ids, seqGapMs, 4000, onComplete);
    return;
  }
  // Per-playAfter context — registered with stopAllAudio so a
  // back-button tap (or any other navigation) can cancel the fallback
  // timer AND detach the `ended` listener. Without this, tapping ←
  // mid-cheer would let the fallback fire ~2s later in the destination
  // scene and start the step audio chain there ("audio still playing
  // after I tapped ←").
  const ctx = { cancelled: false, ref, onEnded: null };
  activeAfters.add(ctx);
  let fired = false;
  const kickoff = () => {
    if (fired || ctx.cancelled) return;
    fired = true;
    clearTimeout(fallback);
    afterFallbackTimers.delete(fallback);
    if (ctx.onEnded) {
      try { ctx.ref.removeEventListener("ended", ctx.onEnded); } catch (_) {}
    }
    activeAfters.delete(ctx);
    playSequence(ids, seqGapMs, gapMs, onComplete);
  };
  // Fallback timer: on iPad Safari the reference cue's `ended` event
  // sometimes never fires after the very first unlock — the play()
  // resolves but the metadata-driven `ended` event is missed, leaving
  // the kid in silence forever. Use the cue's known duration plus a
  // buffer as a wall-clock fallback. Whichever fires first wins.
  const durMs = (Number.isFinite(ref.duration) && ref.duration > 0)
    ? ref.duration * 1000
    : 4000; // generous default for the 3-5s spoken sentences
  const fallback = setTimeout(kickoff, durMs + 1500);
  afterFallbackTimers.add(fallback);
  if (ref.ended) {
    kickoff();
    return;
  }
  ctx.onEnded = function onEnded() {
    ctx.ref.removeEventListener("ended", onEnded);
    kickoff();
  };
  ctx.ref.addEventListener("ended", ctx.onEnded);
}

const k = kaplay({
  width: 1366,
  height: 1024,
  letterbox: true,
  touchToMouse: true,
  canvas: document.getElementById("game"),
  background: [255, 241, 220],
  crisp: true,
  global: false,
});

window.kaplay = k;
window.PandaAudio = { audio, unlockAudio, playCue, playSequence, playAfter, stopAllAudio, isUnlocked: () => audioUnlocked };

// Wrap k.go so any scene transition (level card tap, back button, round
// transition, level-complete) stops the currently-speaking audio first.
// Without this, a kid who taps the L1 card while the L3 round is still
// reading its last cue would hear the rest of the L3 sentence on top of
// the L1 greeting — a wall of sound.
const _origGo = k.go.bind(k);
k.go = (name) => {
  window.PandaAudio.stopAllAudio();
  return _origGo(name);
};

// Art assets are hand-authored SVG under assets/art/. Unlike the level data
// above, these are fetched over HTTP, so the game must be served (see README) —
// double-clicking index.html will start but render without art. Each load is
// guarded individually: a missing or malformed file should cost the game its
// decoration, not its arithmetic. Components check k.getSprite() before drawing.
const SPRITES = [
  "panda-idle", "panda-cheer", "panda-think",
  "bamboo", "leaf",
  "star", "lock",
  "badge-1", "badge-2", "badge-3",
  // panda-park migrated game props
  "boat", "cloud", "mole", "balloon", "bubble",
];

function loadArt() {
  return Promise.all(
    SPRITES.map((name) =>
      Promise.resolve(k.loadSprite(name, `assets/art/${name}.svg`)).catch((err) => {
        console.warn(`[panda] sprite "${name}" failed to load:`, err?.message || err);
        return null;
      }),
    ),
  );
}

function tryLockLandscape() {
  if (!screen.orientation || typeof screen.orientation.lock !== "function") return;
  screen.orientation.lock("landscape").catch(() => {});
}

function watchOrientation() {
  const hint = document.getElementById("rotate-hint");
  if (!hint) return;
  const portrait = () => window.matchMedia("(orientation: portrait)").matches;
  const apply = () => {
    const isCoarse = window.matchMedia("(pointer: coarse)").matches;
    hint.hidden = !(isCoarse && portrait());
  };
  apply();
  window.addEventListener("resize", apply);
  window.addEventListener("orientationchange", apply);
}

document.addEventListener("pointerdown", () => {
  unlockAudio();
  tryLockLandscape();
}, { passive: true, once: false });

watchOrientation();

(async () => {
  window.PandaLevels = levelsData;

  const [
    { default: levelPicker },
    { default: gamesPicker },
    { default: level1 },
    { default: level2 },
    { default: level3 },
    { default: gameBoat },
    { default: gameBounce },
    { default: gameCloud },
    { default: gameFeed },
    { default: gameWhack },
  ] = await Promise.all([
    import("./scenes/levelPicker.js"),
    import("./scenes/gamesPicker.js"),
    import("./scenes/level1.js"),
    import("./scenes/level2.js"),
    import("./scenes/level3.js"),
    import("./scenes/gameBoat.js"),
    import("./scenes/gameBounce.js"),
    import("./scenes/gameCloud.js"),
    import("./scenes/gameFeed.js"),
    import("./scenes/gameWhack.js"),
  ]);

  // Sprites must be resolved before the first scene runs: scenes decide at build
  // time whether a sprite exists, so loading them afterwards would leave the
  // opening screen permanently art-less.
  await loadArt();

  k.scene("levelPicker", () => levelPicker(k));
  k.scene("gamesPicker", () => gamesPicker(k));
  k.scene("level1", () => level1(k));
  k.scene("level2", () => level2(k));
  k.scene("level3", () => level3(k));
  k.scene("gameBoat",   () => gameBoat(k));
  k.scene("gameBounce", () => gameBounce(k));
  k.scene("gameCloud",  () => gameCloud(k));
  k.scene("gameFeed",   () => gameFeed(k));
  k.scene("gameWhack",  () => gameWhack(k));

  k.go("levelPicker");
})();