// scenes/subtractionLevels.js — L6/L7/L8 single-file level module.
//
// v4 redesign (2026-08-16, per user feedback "第二步错了..." →
// "Step 2 should ask the ones-sub"):
//
//   L6 — single interactive step (read equation + pick answer), with
//        per-round step-1 audio ("a 减 b 等于几") and answer read-back.
//        See data/pools.js generateL6Pool for the a === b filter.
//
//   L7 / L8 — same 3-row persistent teaching diagram with ∧ split
//        curves and ∨ combine curves:
//          anchor  "a - b = ?"             y=240   (persistent)
//          split   "? + ? - b = ?"         y=400   (step 1: pick ones)
//          result  "10+diff / ones+sub = ?" y=580  (step 2 + 3: pick diff/sub, then answer)
//        Each step is INTERACTIVE — the kid works through the
//        decomposition themselves:
//          Step 1 ("拆一拆"): pick ones (buttons show "10+5 / 10+7 / ...").
//          Step 2: pick the subtraction result (buttons bare single digits).
//            L7 ("个位相减"): diff = ones - b.  Result row "10 + diff = ?".
//            L8 ("十位相减"): sub  = 10 - b.   Result row "{ones} + sub = ?".
//          Step 3 ("合起来"): pick the final answer.
//            L7: buttons "10+1 / 10+3 / ...".
//            L8: buttons "{ones}+{sub} / ..." (e.g. "2+2 / 2+1 / ...").
//        ? boxes fill in when the kid picks correctly (per user
//        "答对了要填充"). Audio for each step plays BEFORE the next
//        row or pick appears (per user "题目播报完了，再出下一步的").
//
//        Both L7 and L8 use 破十法 (subtract where it fits, keep the
//        other half whole): L7 borrows from ones (b ≤ ones), L8 borrows
//        from 10 (b > ones). Same conceptual strategy, mirrored.
//
// Audio cues (composite, generated by tools/build-audio-tencent.mjs):
//   l6-s1-{a}-{b}                  "{a}减{b}等于几"
//   l6-rwd-{a}-{b}-{answer}        "{a}减{b}等于{answer}"
//   l7-s1-{a}-{b}                  "{a}减{b}等于几，我们先把{a}拆成十加几"
//   l7-s2q-{ones}-{b}              "个位相减{ones}减{b}等于几"   (asks for diff)
//   l7-s2-{ones}-{b}               "个位相减{ones}减{b}等于{diff}" (legacy; states diff)
//   l7-s3-{diff}                   "十加{diff}等于几"
//   l7-rwd-{a}-{b}-{answer}        "{a}减{b}等于{answer}"
//   l8-s1-{a}-{b}                  "{a}减{b}等于几，我们先把{a}拆成十加几"
//   l8-s2-{b}                      "十减{b}等于几"               (asks for sub)
//   l8-s3-{ones}-{b}               "{ones}加{10-b}等于几"        (asks for answer)
//   l8-rwd-{a}-{b}-{answer}        "{a}减{b}等于{answer}"

import createRoundScene, { LAYOUT, options } from "./roundScene.js?v=20260816b";
import { poolGens } from "../data/pools.js?v=20260816b";
import expression from "../components/expression.js?v=20260816b";
import drawLink from "../components/drawLink.js?v=20260816b";
import {
  BLUE, PINK, YELLOW, ORANGE, INK,
} from "../components/theme.js?v=20260816b";

const COL_BIG   = BLUE;    // the 2-digit minuend (a)
const COL_SMALL = PINK;    // the 1-digit subtrahend (b)
const COL_TEN   = YELLOW;  // the literal "10"
const COL_NEED  = ORANGE;  // unknown / just-computed slot

// ---------- shared slot helpers ----------------------------------------

function subtractionSlots(round, answer = "?") {
  return {
    slots: [round.a, "-", round.b, "=", answer],
    colors: [COL_BIG, undefined, COL_SMALL, undefined, answer === "?" ? COL_NEED : undefined],
    reserve: [round.a, "-", round.b, "=", round.answer],
  };
}

// L7/L8 anchor (a - b = ?) — top of the persistent diagram.
function teenAnchorSlots(round, sumSlot) {
  return {
    slots: [round.a, "-", round.b, "=", sumSlot],
    colors: [COL_BIG, undefined, COL_SMALL, undefined, sumSlot === "?" ? COL_NEED : undefined],
    reserve: [round.a, "-", round.b, "=", round.answer],
  };
}

// L7/L8 split row: "? + ? - b = ?" — 7 slots. Slots 0 and 2 reveal to
// the two halves of a's decomposition (10 + ones). Slot 6 is the
// equation's answer; defaults to "?" but step-2 onAdvance passes the
// real answer so the trailing box gets filled alongside the anchor +
// result-row answer (per "答对了要填充").
//
// Default layout (L7, 破十法 in the ones place):
//   slot 0 = 10   (COL_TEN, the "whole" half that carries through)
//   slot 2 = ones (COL_NEED, the "subtracted-from" half)
//
// L8 opts in via { leftColor, rightColor } when slot 0 is the subtracted
// half and slot 2 is the whole one (L8 swaps the decomposition so the
// ones — the digit that stays whole in L8's 破十法 — is shown first):
//   L8 slot 0 = ones (COL_NEED)   L8 slot 2 = 10   (COL_TEN)
function teenSplitSlots(round, leftSlot = "□", rightSlot = "□", answerSlot = "?", opts = {}) {
  const leftColor = opts.leftColor ?? COL_TEN;
  const rightColor = opts.rightColor ?? COL_NEED;
  return {
    slots: [leftSlot, "+", rightSlot, "-", round.b, "=", answerSlot],
    colors: [
      leftColor, undefined, rightColor, undefined,
      COL_SMALL, undefined,
      answerSlot === "?" ? COL_NEED : undefined,
    ],
    // Reserve widest lifetime for stable slot centers across reveals.
    // ones is always 1-9 (single digit), but reserve to "10" so the
    // row layout doesn't reflow if pool math ever loosens.
    reserve: ["10", "+", "10", "-", round.b, "=", round.answer],
  };
}

// L7 result row: "10 + diff = ?" — 5 slots. Slot 2 (diff) is shown
// directly (audio states the diff in step 2); slot 4 is the answer
// box the kid picks. Col_TEN for the 10, COL_NEED for diff (stays
// after reveal), and answer slot cycles COL_NEED → INK on correct.
function l7ResultSlots(round, diff, answerSlot = "?") {
  return {
    slots: [10, "+", diff, "=", answerSlot],
    colors: [COL_TEN, undefined, COL_NEED, undefined, answerSlot === "?" ? COL_NEED : INK],
    reserve: [10, "+", "9", "=", round.answer],
  };
}

// L8 result row: "{ones} + sub = ?" — 5 slots. The 破十法 result row
// (vs L7's "10 + diff = ?") keeps the digit that stays whole in slot 0
// and the digit that gets subtracted-from in slot 2:
//   L7 (不退位, 破十法): slot 0 = 10, slot 2 = diff = ones - b.
//   L8 (退位,  破十法): slot 0 = ones, slot 2 = sub = 10 - b.
// So L8 carries "ones" through and subtracts b from the 10 instead of
// from ones. sub is computed in scene (sub = 10 - round.b); step 2 audio
// (l8-s2-{b}) asks the kid for it, then they pick it in the result row.
// See teenLinkPoints for the matching curve swaps (transform source
// split[0] → result[2] COL_TEN; carry split[2] → result[0] COL_NEED).
function l8ResultSlots(round, sub, answerSlot = "?") {
  return {
    slots: [round.ones, "+", sub, "=", answerSlot],
    colors: [COL_NEED, undefined, COL_NEED, undefined, answerSlot === "?" ? COL_NEED : INK],
    // ones ∈ [1, 8] (single digit, but reserve "9" for safety); sub
    // ∈ [1, 8] same. Answer ∈ [2, 9]. No literal "10" anywhere in
    // this row (unlike L7), so the reserve is narrower than L7's.
    reserve: ["9", "+", "9", "=", round.answer],
  };
}

// ---------- L7/L8 layout ------------------------------------------------

// 3 stacked rows — anchor (top) → split → result (bottom). 160px
// stride gives the ∧/∨ curves enough vertical runway without crowding
// the digits (size 60-80 boxes are ~60-80px tall).
const Y_ANCHOR = 240;
const Y_SPLIT  = 400;
const Y_RESULT = 580;

const ANCHOR_SIZE = 80;
const ROW_SIZE    = 60;

// Renders a single row into ctx[key]. Caller passes the slot layout and
// positioning opts; the function handles destroy + center-on-bar-x.
function renderTeenRow(ctx, key, slots, opts) {
  if (ctx[key]) ctx[key].destroy();
  ctx[key] = expression(ctx.k, {
    ...slots,
    // Centered on the step bar's x (LAYOUT.barX). ctx.arrowsRoot is
    // positioned at (0, 0) for the drawLink parent — using its pos.x
    // would shove the row off to the left edge (regression seen
    // 2026-08-16 in the L7 step-2 screenshot where the split row
    // clipped at x≈0).
    x: LAYOUT.barX,
    y: opts.y,
    size: opts.size,
  });
  return ctx[key];
}

// Returns the array of link points for the L7/L8 diagram. Four lines
// per level, both staying in the same shape across L7 and L8 (just
// with different "from" slots for the split→result arrow):
//   ∧ anchor[0] → split[0]   ("a splits into its ten-half")
//   ∧ anchor[0] → split[2]   ("a splits into its ones-half")
//   ∨ transform: split[transformFrom] → result[resultCenter]
//                L7: split[2]=ones → result[2]=diff
//                L8: split[0]=10   → result[2]=sub
//   ∨ subtrahend: split[4]=round.b → result[resultCenter]
//                "the b we're subtracting leads to the diff/sub"
// Per user feedback 2026-08-16 ("缺少第二行的3到第三行的□ 的线"),
// the subtrahend's connection to the result slot is what was missing.
// Earlier lines that have since been REMOVED:
//   - ∨ split[0] → result[0] (carry, "10 carries through"). User
//     feedback was that this looks redundant — the result row's
//     "10" reads fine on its own.
//   - ∨ anchor[1] → result[0] ("minus sign points to answer").
//     Same redundancy as the carry line.
//   - ∨ split[2] → result[0] (extra "ones → 10"). Pedagogically
//     weak — ones is what gets subtracted, not what becomes the 10.
//
// `resultCenter` (default 2) is the slot index of the sub value
// (diff for L7, sub for L8) in the result row — both at slot 2 of a
// 5-slot row.
//
// Bug fix (2026-08-16): the anchor is rendered via setAnchorEquation
// (roundScene) which stores the node on `ctx.anchorEqNode`, NOT on a
// `ctx.teenAnchorNode` key. The split / result rows ARE stored on
// `ctx.teenSplitNode` / `ctx.teenResultNode` (because renderTeenRow
// uses ctx[key] = expression(...) directly). So this helper has to
// look at `ctx.anchorEqNode` for the anchor and the `teen*` keys for
// the others — otherwise the ! anchor?.slotCenters guard returns
// early and no lines get drawn.
function teenLinkPoints(ctx, opts = {}) {
  const {
    resultCenter = 2,
    transformFrom = 2,
    transformColor = COL_NEED,
    splitLeftColor = COL_TEN,
    splitRightColor = COL_NEED,
  } = opts;
  const pts = [];
  const anchor = ctx.anchorEqNode;
  const split  = ctx.teenSplitNode;
  const result = ctx.teenResultNode;
  if (!anchor?.slotCenters) return pts;

  // ∧ anchor.a → split[0]. Color tracks whatever the slot actually
  // holds — L7 default is COL_TEN (split[0] = "10"); L8 swaps the
  // decomposition so split[0] holds "ones" and the line is COL_NEED.
  if (split?.slotCenters?.[0] != null && anchor.slotCenters[0] != null) {
    pts.push({
      from: { x: anchor.slotCenters[0], y: anchor.slotY + anchor.slotSizes[0] / 2 },
      to:   { x: split.slotCenters[0], y: split.slotY - split.slotSizes[0] / 2 },
      color: splitLeftColor,
      kind: "split",
    });
  }
  // ∧ anchor.a → split[2]. Color tracks the slot's content — L7
  // default is COL_NEED (split[2] = "ones"); L8 swaps so split[2]
  // holds "10" and the line is COL_TEN.
  if (split?.slotCenters?.[2] != null && anchor.slotCenters[0] != null) {
    pts.push({
      from: { x: anchor.slotCenters[0], y: anchor.slotY + anchor.slotSizes[0] / 2 },
      to:   { x: split.slotCenters[2], y: split.slotY - split.slotSizes[2] / 2 },
      color: splitRightColor,
      kind: "split",
    });
  }
  // ∨ transform: split[transformFrom] → result[resultCenter]. See the
  // block comment above for L7 vs L8 specifics.
  if (split?.slotCenters?.[transformFrom] != null && result?.slotCenters?.[resultCenter] != null) {
    pts.push({
      from: { x: split.slotCenters[transformFrom], y: split.slotY + split.slotSizes[transformFrom] / 2 },
      to:   { x: result.slotCenters[resultCenter], y: result.slotY - result.slotSizes[resultCenter] / 2 },
      color: transformColor,
      kind: "combine",
    });
  }
  // ∨ subtrahend: split[4]=round.b → result[resultCenter]. The b
  // we're subtracting leads to the diff/sub. Per user feedback
  // 2026-08-16: "缺少第二行的 3 到第三行的 □ 的线" — without this
  // arrow the kid can't see how the subtrahend connects to the
  // sub-result slot. Both L7 and L8 share this arrow (round.b lives
  // at split[4] in both layouts).
  if (split?.slotCenters?.[4] != null && result?.slotCenters?.[resultCenter] != null) {
    pts.push({
      from: { x: split.slotCenters[4], y: split.slotY + split.slotSizes[4] / 2 },
      to:   { x: result.slotCenters[resultCenter], y: result.slotY - result.slotSizes[resultCenter] / 2 },
      color: COL_SMALL,
      kind: "combine",
    });
  }

  return pts;
}

function redrawTeenLinks(ctx, opts = {}) {
  ctx.arrowNodes?.forEach((n) => n.destroy());
  ctx.arrowNodes = [];
  const pts = teenLinkPoints(ctx, opts);
  // Opacity bumped to 0.55 (was 0.4) — the COL_NEED ones-half line lands
  // as pale peach over cream at 0.4 and was hard to see; L4/L5 use 0.4 on
  // a tighter / darker backdrop so they got away with it. The COL_TEN
  // ten-half line still reads fine at 0.55. Match L4/L5's call shape too:
  // drawLink returns a single node, so spread is wrong (was silently no-op).
  for (const p of pts) {
    ctx.arrowNodes.push(drawLink(ctx.k, ctx.arrowsRoot, p.from, p.to, p.color, 7, 0.55));
  }
}

// ---------- shared audio chain helpers ---------------------------------

// Fires a per-step audio cue chain. Same pattern as L4/L5 (see
// scenes/level5.js::fireL5StepAudio): chain off the cheer chain's last
// cue when there's one (gap 400ms breath), otherwise play immediately
// with a small render-settle delay.
function fireTeenStepAudio(ctx, ids, _stepNumber, onComplete) {
  if (ctx.lastEncourageId) {
    window.PandaAudio.playAfter(ctx.lastEncourageId, ids, {
      gapMs: 400, seqGapMs: 40,
    }, onComplete);
    return;
  }
  window.PandaAudio.playSequence(ids, 40, 100, onComplete);
}

// ---------- L6 audio cue builders --------------------------------------

function buildL6Step1Ids(a, b) { return [`l6-s1-${a}-${b}`]; }
function buildL6RewardIds(a, b, answer) { return [`l6-rwd-${a}-${b}-${answer}`]; }

// ---------- L7 audio cue builders --------------------------------------

function buildL7Step1Ids(a, b) { return [`l7-s1-${a}-${b}`]; }
// Step 2 audio: l7-s2q ASKS for the diff. The kid computes
// "个位相减 {ones} 减 {b}" themselves and picks the diff. Step 2 no
// longer chains l7-s2 (which states the diff) — that cue is retained
// for the legacy audio but no longer plays in this flow. After the
// kid picks the diff, step 3 plays l7-s3 ("十加 {diff} 等于几") as
// the answer prompt.
function buildL7Step2Ids(ones, b) { return [`l7-s2q-${ones}-${b}`]; }
// Step 3 audio: l7-s3 asks for the final answer, "10 + {diff} 等于几".
function buildL7Step3Ids(diff) { return [`l7-s3-${diff}`]; }
function buildL7RewardIds(a, b, answer) { return [`l7-rwd-${a}-${b}-${answer}`]; }

// ---------- L8 audio cue builders --------------------------------------

function buildL8Step1Ids(a, b) { return [`l8-s1-${a}-${b}`]; }
// Step 2 audio: l8-s2 ASKS for sub (the kid mentally computes "10 - b").
// Result row "{ones} + sub = ?" appears after this audio finishes, with
// sub as the pickable slot in the middle.
function buildL8Step2Ids(b) { return [`l8-s2-${b}`]; }
// Step 3 audio: l8-s3 ASKS for the final answer, "{ones} 加 {sub} 等于几".
// Cue id encodes (ones, b) since sub = 10 - b is determined by b. Pass
// the kid the answer's decomposed form so it matches the result row.
function buildL8Step3Ids(ones, b) { return [`l8-s3-${ones}-${b}`]; }
function buildL8RewardIds(a, b, answer) { return [`l8-rwd-${a}-${b}-${answer}`]; }

// ---------- L6 ----------------------------------------------------------

// L6 is a single-step level — the kid reads the equation and picks the
// answer. Per user feedback 2026-08-16 ("没有介绍的声音，用腾讯生成"),
// the per-round step-1 audio IS the entry prompt. After correct pick the
// reward audio reads the full equation as a celebration sentence; the
// advance is gated on that audio finishing (same Promise pattern as L5
// step 5).
export const level1 = createRoundScene({
  levelId: 1,
  sceneName: "level1",
  poolGen: () => poolGens[1](),
  // sampleSize MUST equal DAILY_CAPS[1] (6) so a single play-through
  // finishes today's quota in one go.
  sampleSize: 6,
  stepLabels: ["算一算"],
  // Per user feedback 2026-08-16 ("没有介绍的声音，用腾讯生成"),
  // the per-round step-1 audio IS the entry prompt. After correct pick the
  // reward audio reads the full equation as a celebration sentence; the
  // advance is gated on that audio finishing (same Promise pattern as L5
  // step 5).
  //
  // 2026-08-16: per user "把十以内的减法放到level1，其它的依次移动一个
  // level", this 十以内减法 level moved from L6 to L1. levelId/poolGens
  // updated to match. The cue ID prefix (`l6-*`) is unchanged because
  // the per-round MP3 files are baked under those names.
  steps: [
    (ctx, round) => {
      ctx.setAnchorEquation(subtractionSlots(round), { y: 280, size: 96 });
      fireTeenStepAudio(ctx, buildL6Step1Ids(round.a, round.b), 1);
      return {
        // NO equation — the anchor IS the equation. The previous
        // version rendered the same "a - b = ?" row again at y=460,
        // which made the screen read as "the same equation twice".
        // Per user feedback 2026-08-16: "表达式重复了两次，没必要".
        question: {
          correct: round.answer,
          values: options(round.answer, { min: 0, max: 10 }),
        },
        onAdvance: () => {
          ctx.setAnchorEquation(subtractionSlots(round, round.answer), { y: 280, size: 96 });
          return new Promise((resolve) => {
            window.PandaAudio.playAfter(
              ctx.lastEncourageId,
              buildL6RewardIds(round.a, round.b, round.answer),
              { gapMs: 200, seqGapMs: 40 },
              resolve,
            );
          });
        },
      };
    },
  ],
});

// ---------- L7 ----------------------------------------------------------

// 2 interactive teaching beats per the user's 2026-08-16 sketch. The
// strategy mirrors L5 minus the b decomposition (L7's b fits inside
// ones, no need to split it) — only `a` is decomposed into 10 + ones,
// and the result of `ones - b` (the diff) lands on the teen's tens
// (still 10) so step 2 is just "10 + diff = ?".
//
//   anchor   "a - b = ?"           y=240   (persistent)
//   split    "? + ? - b = ?"       y=400   (step 1: pick ones)
//   result   "10 + diff = ?"       y=580   (step 2: pick answer; diff auto-shown)
//
// Step 1 audio: l7-s1 ("a 减 b 等于几，我们先把 a 拆成十加几").
// Step 2 audio: l7-s2 + l7-s3 chained ("个位相减 ones 减 b 等于 diff" +
// "十加 diff 等于几"). The diff reveals to the value when the result
// row renders after l7-s2 finishes; the kid then picks the answer for
// l7-s3.
const l7Steps = [
  // Step 1 — 拆 a. Anchor + split row appear, kid picks ones (the
  // second ?). After pick, split row reveals to "10 + ones - b = ?".
  (ctx, round) => {
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    fireTeenStepAudio(ctx, buildL7Step1Ids(round.a, round.b), 1, () => {
      renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round), { y: Y_SPLIT, size: ROW_SIZE });
      redrawTeenLinks(ctx);
    });
    return {
      question: {
        correct: round.ones,
        // Step 1 options: ones digit, [1, 9]. ones ≥ 1 by pool rule.
        values: options(round.ones, { min: 1, max: 9 }),
        // Render decomposition options as "10+5 / 10+7 / 10+6 / 10+8"
        // instead of bare digits — the kid is being asked to fill the
        // ones-part of the split row, so seeing every option in the same
        // "10+?" shape matches the prompt ("拆成十加几") and the slot
        // it's filling. Per user feedback 2026-08-16: "选项应该是
        // 10+5 10+7，10+6，10+8". Same labelFor pattern as L4 step 1
        // (level4.js:343).
        labelFor: (v) => `10+${v}`,
      },
      onAdvance: () => {
        renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, 10, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
        redrawTeenLinks(ctx);
      },
    };
  },

  // Step 2 — 个位相减. Anchor + split (revealed) stay. Result row
  // "10 + □ = ?" appears AFTER the l7-s2q audio asks for the diff
  // ("个位相减 {ones} 减 {b} 等于几"). Kid picks the diff (the ones-digit
  // result of the subtraction). Per user feedback 2026-08-16: "第二步
  // 应该是 九减八等于几" — the ones sub is now a teaching beat the
  // kid works through, not a value the audio just states. Step 3
  // then prompts for the final answer ("十加 {diff} 等于几") once the
  // kid has the diff in hand.
  (ctx, round) => {
    const diff = round.ones - round.b;
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, 10, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
    fireTeenStepAudio(ctx, buildL7Step2Ids(round.ones, round.b), 2, () => {
      // Result row's diff slot (slot 2) renders as "□" so the kid has
      // somewhere to land the diff. The trailing "=" answer slot (slot
      // 6) keeps a COL_NEED placeholder until step 3 picks the answer.
      renderTeenRow(ctx, "teenResultNode", l7ResultSlots(round, "□"), { y: Y_RESULT, size: ROW_SIZE });
      redrawTeenLinks(ctx);
    });
    return {
      question: {
        correct: diff,
        // Diff range [0, 8]: ones ∈ [1, 9], b ∈ [1, ones], so
        // diff = ones - b lands in [0, 8]. Bare single digits — the
        // row "10 + □ = ?" reads the diff as a single digit so the
        // "10+?" decomposed form would only confuse at this stage.
        values: options(diff, { min: 0, max: 8 }),
      },
      onAdvance: () => {
        // Reveal diff in the result row (slot 2). Anchor and split
        // are unchanged from step 1's onAdvance. The trailing "?"
        // (slot 6) stays as a placeholder until step 3 picks it.
        renderTeenRow(ctx, "teenResultNode", l7ResultSlots(round, diff), { y: Y_RESULT, size: ROW_SIZE });
        redrawTeenLinks(ctx);
      },
    };
  },

  // Step 3 — 合起来. Anchor + split + result-with-diff all stay from
  // step 2. The l7-s3 audio plays ("十加 {diff} 等于几"), then the kid
  // picks the final answer. Per user feedback 2026-08-16: "答对了要
  // 填充" still applies — once the answer is picked, every □ across
  // the persistent diagram reveals to the value.
  (ctx, round) => {
    const diff = round.ones - round.b;
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, 10, round.ones), { y: Y_SPLIT, size: ROW_SIZE });
    renderTeenRow(ctx, "teenResultNode", l7ResultSlots(round, diff), { y: Y_RESULT, size: ROW_SIZE });
    fireTeenStepAudio(ctx, buildL7Step3Ids(diff), 3, () => {
      // No new row appears — the kid is looking at "10 + {diff} = ?"
      // and needs to pick the final answer.
    });
    return {
      question: {
        correct: round.answer,
        // Answer range: [10, 18] (a ∈ [11,19], b ∈ [1, ones] → answer
        // ∈ [a - ones, a - 1] ⊆ [10, 18]). Buttons stay as BARE
        // integers — the result row's "10 + diff = ?" prompt IS the
        // decomposed view, so showing "10+1 / 10+3 / ..." on the
        // buttons would be redundant ("10+0 = ?" with button "10+1"
        // reads as "pick the addition that goes with this row", not
        // "the answer is 11"). Per user feedback 2026-08-16:
        // "10+0等于几，应该是10，11，12，13 这些选项."
        values: options(round.answer, { min: 10, max: 18 }),
      },
      onAdvance: () => {
        // Reveal the answer in the anchor (slot 4), the split row's
        // trailing "?" (slot 6), AND the result row's slot 4. Per user
        // feedback 2026-08-16 "答对了要填充": every □ gets filled when
        // the kid picks correctly, including the split row's trailing
        // "=" placeholder that otherwise reads as an unanswered
        // question. Persistent diagram stays — only the answer slots
        // are rewritten, per the L4 step-3 lesson on not tearing rows.
        ctx.setAnchorEquation(teenAnchorSlots(round, round.answer), { y: Y_ANCHOR, size: ANCHOR_SIZE });
        renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, 10, round.ones, round.answer), { y: Y_SPLIT, size: ROW_SIZE });
        renderTeenRow(ctx, "teenResultNode", l7ResultSlots(round, diff, round.answer), { y: Y_RESULT, size: ROW_SIZE });
        redrawTeenLinks(ctx);
        return new Promise((resolve) => {
          window.PandaAudio.playAfter(
            ctx.lastEncourageId,
            buildL7RewardIds(round.a, round.b, round.answer),
            { gapMs: 200, seqGapMs: 40 },
            resolve,
          );
        });
      },
    };
  },
];

export const level7 = createRoundScene({
  levelId: 7,
  sceneName: "level7",
  poolGen: () => poolGens[7](),
  // sampleSize MUST equal DAILY_CAPS[7] (8) so a single play-through
  // finishes today's quota in one go.
  sampleSize: 8,
  stepLabels: ["拆一拆", "个位相减", "合起来"],
  steps: l7Steps,
});

// ---------- L8 ----------------------------------------------------------

// Same 3-row layout as L7 (per user "level8:也要像这样改造"), but the
// 凑十法 strategy is 破十法 (vs L7's also 破十法 in the ones place): the
// ten is subtracted from instead of the ones, since b > ones here.
//   1. Split a into 10 + ones (kid picks ones, step 1).
//   2. sub = 10 - b is asked via l8-s2-{b} audio ("十减 b 等于几"); the
//      result row "{ones} + sub = ?" appears with sub to be picked.
//   3. Answer = ones + sub is asked via l8-s3-{ones}-{b} audio
//      ("{ones} 加 {sub} 等于几"); kid picks the answer.
//
// ∨ curve roles (see teenLinkPoints for the math):
//   transform: split[2]=10 → result[2]=sub, COL_TEN  ("10 - b = sub")
//   subtrahend: split[4]=b → result[2]=sub, COL_SMALL  ("b connects to sub")

// L8 opts reused across all 3 step functions — the 破十法 swap (ones
// first, ten second in the split row) puts the ten at split[2] and
// the ones at split[0], so transformFrom flips from L7's 2 to 2 (no
// change at the index level, but the color track does). The ∧ lines
// also flip colors since split[0] now holds ones (COL_NEED) and
// split[2] holds 10 (COL_TEN).
const L8_SPLIT_COLORS = { leftColor: COL_NEED, rightColor: COL_TEN };
const L8_LINK_OPTS = {
  transformFrom: 2,
  transformColor: COL_TEN,
  splitLeftColor: COL_NEED,
  splitRightColor: COL_TEN,
};

const l8Steps = [
  // Step 1 — 拆 a. Split row order is "ones + 10 - b = ?" (swapped
  // from L7's "10 + ones - b = ?") so the digit that stays whole in
  // L8's 破十法 (ones) is shown first. Per user feedback 2026-08-16
  // ("第二步的顺序应该是 2+10-6").
  (ctx, round) => {
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    fireTeenStepAudio(ctx, buildL8Step1Ids(round.a, round.b), 1, () => {
      renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round), { y: Y_SPLIT, size: ROW_SIZE });
      redrawTeenLinks(ctx, L8_LINK_OPTS);
    });
    return {
      question: {
        correct: round.ones,
        values: options(round.ones, { min: 1, max: 8 }),
        // Swapped from L7's "10+?" — matches the "ones + 10" split
        // row so the button shows the same shape as the slot it
        // fills. For ones=2 the kid sees "2+10" as the button label.
        labelFor: (v) => `${v}+10`,
      },
      onAdvance: () => {
        renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, round.ones, 10, "?", L8_SPLIT_COLORS), { y: Y_SPLIT, size: ROW_SIZE });
        redrawTeenLinks(ctx, L8_LINK_OPTS);
      },
    };
  },

  // Step 2 — 十位相减. Anchor + split (revealed) stay. Result row
  // "{ones} + □ = ?" appears AFTER the l8-s2 audio asks for sub
  // ("十减 {b} 等于几"). Kid picks sub.
  (ctx, round) => {
    const sub = 10 - round.b;
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, round.ones, 10, "?", L8_SPLIT_COLORS), { y: Y_SPLIT, size: ROW_SIZE });
    fireTeenStepAudio(ctx, buildL8Step2Ids(round.b), 2, () => {
      // Sub slot (slot 2) renders as "□" for the kid to land the
      // ten-place subtraction. Trailing answer slot stays a
      // COL_NEED placeholder until step 3.
      renderTeenRow(ctx, "teenResultNode", l8ResultSlots(round, "□"), { y: Y_RESULT, size: ROW_SIZE });
      redrawTeenLinks(ctx, L8_LINK_OPTS);
    });
    return {
      question: {
        correct: sub,
        // Sub range [1, 8]: b ∈ [2, 9], so sub = 10 - b ∈ [1, 8].
        // Bare single digits — the row reads "{ones} + □ = ?" and
        // the kid mentally reduces 10 - b to get sub.
        values: options(sub, { min: 1, max: 8 }),
      },
      onAdvance: () => {
        // Reveal sub in the result row (slot 2). The trailing "?"
        // (slot 4) stays a placeholder until step 3 picks the
        // answer.
        renderTeenRow(ctx, "teenResultNode", l8ResultSlots(round, sub), { y: Y_RESULT, size: ROW_SIZE });
        redrawTeenLinks(ctx, L8_LINK_OPTS);
      },
    };
  },

  // Step 3 — 合起来. Anchor + split + result-with-sub all stay from
  // step 2. The l8-s3 audio plays ("{ones} 加 {sub} 等于几"), then
  // the kid picks the final answer. Per user feedback 2026-08-16
  // "答对了要填充" still applies — once the answer is picked, every □
  // across the persistent diagram reveals to the value.
  (ctx, round) => {
    const sub = 10 - round.b;
    // Reorder options so the correct answer lands in position 3
    // (0-indexed 2). The default outward-walk order is
    // [correct, +1, -1, +2]; for 12-6 that gives [6, 7, 5, 8].
    // Per user feedback 2026-08-16 ("最后一步的选项应该是 5，7，6，8")
    // we want distractors sorted ascending with correct inserted at
    // index 2: [-1, +1, correct, +2] for 12-6 → [5, 7, 6, 8]. For
    // edge cases where correct already sits at position 3 (or the
    // distractors don't form a clean [-1, +1, +2] set), we leave
    // the outward-walk order alone — e.g. 11-9 (=2) yields
    // [3, 4, 2, 5] which is unusual but readable.
    const rawOpts = options(round.answer, { min: 2, max: 10 });
    const correctIdx = rawOpts.indexOf(round.answer);
    const orderedOpts =
      correctIdx !== 2 && rawOpts.length === 4
        ? (() => {
            const distractors = rawOpts.filter((v) => v !== round.answer)
              .sort((a, b) => a - b);
            return [...distractors.slice(0, 2), round.answer, ...distractors.slice(2)];
          })()
        : rawOpts;
    ctx.setAnchorEquation(teenAnchorSlots(round, "?"), { y: Y_ANCHOR, size: ANCHOR_SIZE });
    renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, round.ones, 10, "?", L8_SPLIT_COLORS), { y: Y_SPLIT, size: ROW_SIZE });
    renderTeenRow(ctx, "teenResultNode", l8ResultSlots(round, sub), { y: Y_RESULT, size: ROW_SIZE });
    fireTeenStepAudio(ctx, buildL8Step3Ids(round.ones, round.b), 3, () => {
      // No new row appears — the kid looks at "{ones} + {sub} = ?"
      // and picks the final answer.
    });
    return {
      question: {
        correct: round.answer,
        // Answer range: [2, 9] for the borrow case (a ∈ [11,19],
        // b > ones → answer = ones + (10 - b) ∈ [2, 9]).
        values: orderedOpts,
        // Plain answer value on each button (NOT the decomposed
        // "{ones}+{sub}" form). Per user feedback 2026-08-16: "第
        // 三步都要出答案，你还给表达式". The decomposition lives in the
        // result row ("6 + sub = ?"); the buttons just need to be
        // the four candidate answers for the kid to scan and pick.
        labelFor: (v) => String(v),
      },
      onAdvance: () => {
        // Fill the anchor (slot 4), split row (slot 6), and result
        // row (slot 4) with the answer — per "答对了要填充".
        ctx.setAnchorEquation(teenAnchorSlots(round, round.answer), { y: Y_ANCHOR, size: ANCHOR_SIZE });
        renderTeenRow(ctx, "teenSplitNode", teenSplitSlots(round, round.ones, 10, round.answer, L8_SPLIT_COLORS), { y: Y_SPLIT, size: ROW_SIZE });
        renderTeenRow(ctx, "teenResultNode", l8ResultSlots(round, sub, round.answer), { y: Y_RESULT, size: ROW_SIZE });
        redrawTeenLinks(ctx, L8_LINK_OPTS);
        return new Promise((resolve) => {
          window.PandaAudio.playAfter(
            ctx.lastEncourageId,
            buildL8RewardIds(round.a, round.b, round.answer),
            { gapMs: 200, seqGapMs: 40 },
            resolve,
          );
        });
      },
    };
  },
];

export const level8 = createRoundScene({
  levelId: 8,
  sceneName: "level8",
  poolGen: () => poolGens[8](),
  // sampleSize MUST equal DAILY_CAPS[8] (8) so a single play-through
  // finishes today's quota in one go.
  sampleSize: 8,
  // Step 2 label parallels L7's "个位相减" with the borrow-place flipped:
  // L7 subtracts in the ones place (ones ≥ b), L8 subtracts in the tens
  // place (b > ones). Step 1 ("拆一拆") and step 3 ("合起来") are
  // identical across both.
  stepLabels: ["拆一拆", "十位相减", "合起来"],
  steps: l8Steps,
});