// components/whackHole.js — one hole + its pop-out mole for gameWhack.
//
// Each hole owns four Kaplay entities: a hole sprite (one of three variants,
// each an AI-generated 3D elliptical green-grass hole), a mole sprite that
// pops up from below the hole rim, a yellow badge circle for the number,
// and the digit text. The grass-ground tile behind the holes is rendered
// once by gameWhack.js, not per-hole — see SPEC.md in the design doc.
//
// The mole sprite was regenerated by MiniMax text-to-image (2026-08-13);
// the brown dirt baked into the previous mole.svg is gone. The mole is
// drawn at z=1, *behind* the hole sprite (z=2), so the hole's grass rim
// covers the mole's lower body and paws. Only the head pokes above the
// hole — reads as "popping out of the meadow", not "standing in front of
// a hole". See docs/superpowers/specs/2026-08-13-whack-grass-retheme-design.md
// for the full z-order rationale and the user's reference image.
//
// API:
//   whackHole(k, { x, y, variant }) → hole
//   hole.popUp(value)        — show mole with number, auto-retreat after HOLE_DWELL
//   hole.retreat()           — force-hide the mole immediately
//   hole.setSelected(bool)   — toggle the badge's selection highlight (orange/yellow)
//   hole.flashWrong()        — brief shake of the mole sprite (wrong pair feedback)
//   hole.shake()             — x-axis shake, used when this hole is the 2nd pick
//                              of a wrong pair (called by the tap handler)
//
// The badge and number carry the kid's selected/incorrect state, just like
// the inlined implementation they replaced.

import { INK, YELLOW, ORANGE } from "./theme.js?v=20260813";

const HOLE_DWELL = 5.0;       // seconds a mole stays up before retreating

// Hole sprites are 1248×832 (AI-generated 3:2, after the JPG→PNG round-trip
// with transparent background — see tools/_make-transparent.mjs).
// At HOLE_SCALE 0.20 the on-screen footprint is ~250×166 — narrower than
// the 320-cell (so hole sprites don't bleed into each other horizontally)
// and shorter than the 240-cell row gap (so row 0's sprite bottom at
// hole.y + 83 sits well above row 1's sprite top at hole2.y − 83, leaving
// a 74-pixel gap for the bottom-row mole's face to peek into).
//
// Sprite bounds at this scale: top edge at hole.y − 83, bottom at hole.y + 83.
const HOLE_SCALE = 0.20;

// Mole sprite is 1024×1024 (AI-generated, peek pose — see tools/_mole-transparent.mjs
// for the white→transparent conversion). At MOLE_SCALE 0.16 the on-screen
// footprint is ~164×164 — slightly smaller than the hole sprite, which
// lets the mole peek over the rim without dominating the cell.
const MOLE_SCALE = 0.16;

// hole.y + MOLE_Y_OFFSET → mole.y. −120 puts the top of the row-0 mole's
// head ~120px above the row-0 hole's top edge (so ears + forehead poke
// above the rim), and the top of the row-1 mole's head lands in the gap
// between the two hole sprites (so face is visible without overlap with
// either row's grass rim).
const MOLE_Y_OFFSET = -120;

// Badge sits on the mole's forehead. The forehead in the source sprite is
// at y ≈ 300-400 (out of 1024). With MOLE_SCALE 0.16 the forehead lands
// at scene y ≈ mole.y − 30, which is hole.y + (MOLE_Y_OFFSET − 30).
// BADGE_Y_OFFSET = MOLE_Y_OFFSET − 30 keeps the badge on the forehead
// for both rows without falling inside the adjacent hole sprite.
const BADGE_Y_OFFSET = -150;

export default function whackHole(k, { x, y, variant }) {
  // Clamp variant to 0..2 — gameWhack.js already seeds the assignment but
  // a stray caller should never crash on a 3rd-index sprite that doesn't
  // exist (we only generated mole-hole-1..3).
  const v = ((variant % 3) + 3) % 3;

  // Hole sprite: full grass-patch + dark elliptical hole. Drawn ON TOP of
  // the mole (z 2 > z 1) so the hole's grass rim covers the mole's lower
  // body. The mole's head pokes above the sprite's top edge because of
  // MOLE_Y_OFFSET.
  const hole = k.add([
    k.sprite(`mole-hole-${v + 1}`),
    k.pos(x, y),
    k.anchor("center"),
    k.scale(HOLE_SCALE),
    k.z(2),
  ]);

  // Mole sprite: rendered behind the hole, only visible where its head
  // extends above the hole sprite's top edge.
  const mole = k.add([
    k.sprite("mole"),
    k.pos(x, y + MOLE_Y_OFFSET),
    k.anchor("center"),
    k.scale(MOLE_SCALE),
    k.opacity(0),
    k.z(1),
  ]);

  // Number badge + digit. The badge sits on the mole's forehead — see
  // BADGE_Y_OFFSET comment above for the geometry derivation.
  const badge = k.add([
    k.circle(28),
    k.color(...YELLOW),
    k.outline(3, k.rgb(...INK)),
    k.pos(x, y + BADGE_Y_OFFSET),
    k.anchor("center"),
    k.opacity(0),
    k.z(3),
  ]);
  const num = k.add([
    k.text("0", { size: 36, font: "Arial Rounded MT Bold, Trebuchet MS, system-ui, sans-serif" }),
    k.color(...INK),
    k.pos(x, y + BADGE_Y_OFFSET),
    k.anchor("center"),
    k.opacity(0),
    k.z(4),
  ]);

  const state = {
    occupied: false,
    value: null,
    bobPhase: 0,
  };

  function popUp(value) {
    state.occupied = true;
    state.value = value;
    state.bobPhase = 0;
    num.text = String(value);
    mole.opacity = 1;
    badge.opacity = 1;
    num.opacity = 1;
    const start = k.time();
    const baseY = y + MOLE_Y_OFFSET;
    mole.onUpdate(() => {
      const t = k.time() - start;
      if (state.finishedForceRetreat) {
        mole.onUpdate(() => {});
        return;
      }
      if (t > HOLE_DWELL) {
        // Retreat on dwell timeout — only if not already retreated.
        if (state.occupied) {
          mole.opacity = 0;
          badge.opacity = 0;
          num.opacity = 0;
          state.occupied = false;
          state.value = null;
        }
        mole.onUpdate(() => {});
        return;
      }
      // Tiny bob: ±6px vertical, 8 rad/s.
      mole.pos.y = baseY - Math.sin(t * 8) * 6;
    });
  }

  function retreat() {
    state.occupied = false;
    state.value = null;
    state.finishedForceRetreat = true;
    mole.opacity = 0;
    badge.opacity = 0;
    num.opacity = 0;
    // mole.onUpdate is already a no-op once finishedForceRetreat is set,
    // so no extra teardown needed. We deliberately don't reset
    // finishedForceRetreat — this hole is done with this mole, and any
    // subsequent popUp() will start a fresh onUpdate chain.
  }

  function setSelected(on) {
    badge.color = k.rgb(...(on ? ORANGE : YELLOW));
  }

  // Shake the mole sprite horizontally — used by the tap handler when the
  // kid picks a wrong pair. Restores to the hole's resting x after 400ms.
  function shake() {
    const start = k.time();
    const baseX = x;
    const baseY = y + MOLE_Y_OFFSET;
    mole.onUpdate(() => {
      const t = k.time() - start;
      if (t > 0.4) {
        mole.pos.x = baseX;
        mole.pos.y = baseY;
        mole.onUpdate(() => {});
        return;
      }
      mole.pos.x = baseX + Math.sin(t * 30) * 12;
      // Stop the bob while shaking so the two animations don't fight.
      mole.pos.y = baseY;
    });
  }

  return {
    x, y,
    variant: v,
    get occupied() { return state.occupied; },
    get value() { return state.value; },
    popUp, retreat, setSelected, shake,
  };
}